### PR TITLE
Created autophagosome-dependent secretion; #27757

### PR DESCRIPTION
**Pull request by raymond91125**

### CODE REVIEW

**Comment by raymond91125** [comment]
@balhoff Could you help with this error? Thanks. "/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)"

**Comment by balhoff** [comment]
@raymond91125 you can ignore errors in any job except for `CI / ontology_qc`. But that one looks like some kind of internal GitHub problem.

**Comment by raymond91125** [comment]
I don't think I can merge though.

**Comment by raymond91125** [comment]
Figured it out. Thanks.

**Pull request merged**
