### PR TITLE
Added new term Fixes geneontology/synapse#198

### PR DESCRIPTION
**Pull request by BarbaraCzub**
cc
@thomaspd 
@RLovering

### CODE REVIEW

**Review by ukemi — CHANGES_REQUESTED** [review]
Hi @BarbaraCzub ,

If you have an equivalence axiom, you don't need to assert an is_a parent. The reasoner will do this for you. As long as your equivalence axioms are necessary and sufficient, this is the best way to go. Run the reasoner as a sanity check. Note, I am not commenting on the biology on these requests. I am assuming you know more than me.

**Comment by BarbaraCzub** [comment]
Hi @ukemi 
The asserted parent did not come up, when I ran the reasoner:
screen shot 2018-04-18 at 16 05 28
So I left the asserted parent as it was. 
Or should I have modifier the equivalence axiom? 
Thanks,
Barbara

cc
@dosumis

**Comment by ukemi** [comment]
Did you delete the asserted one and did it come back when you resynched the reasoner? It should come back or a more specific correct one should appear.

**Comment by BarbaraCzub** [comment]
Hi @ukemi 
Thank you for your help. 
I have removed the is_a parent/relation and Travis checks passed.
Do you have other comments, or can I merge this? 
Thanks,
Barbara

**Review by ukemi — APPROVED** [review]

**Pull request merged**
