### PR TITLE
removed gosubset_prok fixes #16077

### LINKED ISSUE #16077: Proposal to obsolete/retire the gosubset_prok slim
Dear all, 

The gosubset_prok is very out of date and very incorrect (for example it contains terms such as    GO:0048488  synaptic vesicle endocytosis). The GO ontology editors propose to retire this subset. 

The purpose that this subset served when it was created can now be met with taxon constraints. 

Please let us know if you have any concerns or objections. 

Thanks, Pascale

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by Ayllonbe** [comment]
Hi! where are the taxon constraints in GO?

**Comment by pgaudet** [comment]
Hi @Ayllonbe , 

In the OBO file, they are under

relationship: only_in_taxon NCBITaxon:2 ! Bacteria
relationship: never_in_taxon NCBITaxon:2 ! Bacteria

Thanks, Pascale

**Comment by Ayllonbe** [comment]
I found it, thanks @pgaudet !!

Do you know when that will be available in owl format?

**Comment by pgaudet** [comment]
For some reason (probably file size) I cannot easily download the owl file to check, but I would expect it to be there under the same tags. Can you not see it ? 

Pascale

**Comment by Ayllonbe** [comment]
No, I can't, I downloaded the go.owl from the website and the ftp. I only saw that:

 <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Includes Ontology(OntologyID(OntologyIRI(&lt;http://purl.obolibrary.org/obo/go/never_in_taxon.owl&gt;))) [Axioms: 18 Logical Axioms: 0]</rdfs:comment>

However, I don't know how to download the "never_in_taxon.owl". In obo, we can find the relationship only in the GitHub release "go-edit.obo"

Aaron

**Comment by pgaudet** [comment]
Hi @Ayllonbe 
For some reason I cannot download the owl file. However we have a file in the repo named 'enhanced-owl', which I assume is constructed the same was as the go-owl. This is what a 'never_in_taxon' term looks like: 

 

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0000131">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/GO_0044424"/>
        <owl:disjointWith>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002162"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/NCBITaxon_4895"/>
            </owl:Restriction>
        </owl:disjointWith>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The portion of the budding yeast plasma membrane where a daughter cell will emerge. The yeast marks this spot with bud-site selection proteins before bud emergence occurs. Actin is polarized to this spot just prior to and during bud emergence.</obo:IAO_0000115>
        **<obo:RO_0002161 rdf:resource="http://purl.obolibrary.org/obo/NCBITaxon_4895"/>**
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">cellular_component</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GO:0000131</oboInOwl:id>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">incipient cellular bud site</rdfs:label>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/GO_0000131"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The portion of the budding yeast plasma membrane where a daughter cell will emerge. The yeast marks this spot with bud-site selection proteins before bud emergence occurs. Actin is polarized to this spot just prior to and during bud emergence.</owl:annotatedTarget>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GOC:clt</oboInOwl:hasDbXref>
    </owl:Axiom>

**Comment by Ayllonbe** [comment]
Hi @pgaudet ,

I don't see that in the "go.owl", but I found it in the "go-plus.owl". 

Thank you

Aaron

**Comment by pgaudet** [comment]
Ah ok, good. 

So, to clarify: to get the 'prokaryote-relevant' set you should exclude anything that has 'never in bacteria' or 'only in eukaryotes' (and subclasses of eukaryotes). Does that answer your question?

**Comment by Ayllonbe** [comment]
Yes!

Absolutely!!

Thanks a lot.

**Comment by pgaudet** [comment]
Great, thanks!

**Pull request merged**
