### PR TITLE
First draft at adding cellular anatomical entity to CC ontology.

### PR DESCRIPTION
**Pull request by vanaukenk**

### CODE REVIEW

**Comment by vanaukenk** [comment]
I've made a first draft of the CC ontology with three terms directly under CC:

cell
cellular anatomical entity
protein-containing complex

I updated some asserted parentage and some logical definitions to place terms where I think they ought to be.  Please take a look and add comments/suggestions.  

Thanks.

**Comment by vanaukenk** [comment]
Discussion with @ukemi 

If we move 'cell part' underneath 'cellular anatomical entity', we will still have some protein-containing complexes that are classified as 'cellular anatomical entity', which is what we're trying to avoid.

A possible solution would be to assert that non-protein-containing complexes that are a 'cell part' are a 'cellular anatomical entity' and then remove the various 'cell part' terms.

This needs more discussion, but might be a satisfactory solution.

**Comment by pgaudet** [comment]
One inconsistency is that 'virion' is a child of the new 'cellular anatomical entity', which is defined as "A part of a cellular organism (...); viruses are not cellular organisms. 

We could simply have 'virion' as a separate branch. 
Otherwise - looks great ! 

Pascale

**Comment by vanaukenk** [comment]
Update:

Create 'cellular anatomical entity' term and add definition based on CARO 'anatomical entity' term.

'cellular anatomical entity' would be one of five direct children of cellular_component:
1. cell
2. cellular anatomical entity
3. protein-containing complex
4. virion
5. virion part

Assert 'cellular anatomical entity' parentage for non-'part' terms that are also not protein-containing complexes.

Then, merge existing 'part' terms into their parent, e.g. 'nuclear part' into 'nucleus', as these terms will no longer be needed since the CC ontology will now be 'is a' complete with the additional of 'cellular anatomical entity'.

Consider better ways of representing 'virion' and 'virion part' in GO, in conversation with CARO editors.

**Comment by vanaukenk** [comment]
Action items:
1) Create a ticket in CARO to make organism or virus or viriod a biological entity
2) Once 1 is done, align CARO and GO CC appropriately.
3) Assert parentage for non-part terms
4) Obsolete 'x part' terms in GO and re-annotate to parent term.

**Comment by vanaukenk** [comment]
See: https://github.com/obophenotype/caro/issues/19

**Comment by balhoff** [comment]
Here's the OWL diff for this PR: https://stars-app.renci.org/owldiff/diff?left=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fraw%2F41e1ad3f46aa05004c2671dce4d0140292b90ed9%2Fsrc%2Fontology%2Fgo-edit.obo&right=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fraw%2Fa9da03935d9633a768d6d0719c533c2bcfc79625%2Fsrc%2Fontology%2Fgo-edit.obo&loadimports=true

**Comment by vanaukenk** [comment]
@bahlhoff - this looks okay, except that we had decided to make 'virion' and 'virion part' direct children of 'cellular component' which wasn't done yet.

**Comment by balhoff** [comment]
@vanaukenk the link should update with any additional commits pushed to this branch.

**Pull request merged**
