### PR TITLE
Added terms for protein decrotonylase activity. Fixes #22351

### LINKED ISSUE #22351: NTR: [Protein decrotonylase activity] etc.
Hi GO,

I would need a bunch of GO terms, some of them will be used for GO-CAM models. 

These terms are related to enzymes that remove acylations on lysine residues on proteins. Please note that terms for enzyme that add these modifications already exist. I also request more precise terms when histones are substrates.

Terms are related to Rhea terms, most of them are not yet public (@amorgat @kaxelsen). 

Thanks

Sylvain

1)
Protein decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[protein] = (2E)-2-butenoate + L-lysyl-[protein]
Parent term: GO:0016811 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
PMID:28497810
PMID:34608293
PMID:30279482
Xref: RHEA:69172 (not yet public)

2)
Histone decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone] = (2E)-2-butenoate + L-lysyl-[histone]
child of Protein decrotonylase activity
PMID:28497810

3)
Protein de-2-hydroxyisobutyrylase activity
Catalysis of the reaction: H2O + N6-(2-hydroxyisobutanoyl)-L-lysyl-[protein] = 2-hydroxy-2-methylpropanoate + L-lysyl-[protein] and
Parent term: GO:0016811 hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
PMID:29192674
Xref: RHEA:69176 (not yet public)

4) 
NAD-dependent protein decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[protein] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[protein] + nicotinamide
child of GO:0016747 acyltransferase activity, transferring groups other than amino-acyl groups 
PMID:28497810
Xref: RHEA:69332 (not yet public)

5)
NAD-dependent histone decrotonylase activity
Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[histone] + nicotinamide
child of NAD-dependent protein decrotonylase activity
PMID:28497810

6)
NAD-dependent protein de-2-hydroxyisobutyrylase activity
Catalysis of the reaction: H2O + N6-(2-hydroxyisobutanoyl)-L-lysyl-[protein] + NAD+ = 2''-O-(2-hydroxyisobutanoyl)-ADP-D-ribose + L-lysyl-[protein] + nicotinamide 
child of GO:0016747 acyltransferase activity, transferring groups other than amino-acyl groups 
PMID:31328167
Xref: RHEA:10164 (public)

7)
Last but not least, would it be possible to complete the following mappings to Rhea?

GO:0140065 peptide butyryltransferase activity
Xref: RHEA:53912

GO:0140064 peptide crotonyltransferase activity 
Xref: RHEA:53908

### PR DESCRIPTION
**Pull request by raymond91125**

### CODE REVIEW

**Review by pgaudet — COMMENTED** [review]
Looks good (except for the RHEA error). Note that we are inconsistent using the brackets around protein; I personally dont like it because it's unnecessary characters, but maybe it's easier, since we can just copy the RHEA reaction 

@hdrabkin any opinion?

**Comment by hdrabkin** [comment]
Remember most of those RHEAs are warnings that the link doesn't exist yet  Those don't cause a failure.

Your RHEA:53908 IS in RHEA 
What is your other error?

H

**Comment by hdrabkin** [comment]
I see RHEA:10164 IS in RHEA, but the link in the error log goes to 'not found' (and has nothing to do with this enry I think.

**Comment by hdrabkin** [comment]
As for square brackets around the protein part, I think that's fine. 
Parentheses (round brackets, curves), square brackets, and braces (curly brackets) are used in chemical nomenclature to set off parts of a name dealing with specific structural features in order to convey the structure of a compound as clearly as possible. 
see https://www.acdlabs.com/iupac/nomenclature/93/r93_61.htm

parentheses to form subgroups of atoms within a molecule.
braces (brackets) are often used for nesting  eg TiCl2[(CH3)2PCH2CH2P(Ch3)2]2 (in a pub, all numbers subscripted).

**Comment by hdrabkin** [comment]
And I found BIochemcial NOmenclature and related Documents, 2nd ed 1992 on my shelf
Page 331' Parentheses and square brackets in Chemical formulae (1981)
Use parentheses in a formulae for side chains (CH3, etc.), and square brackets for condensed chains (eg, protein: so you don't have to write out the entire chain!).

**Comment by raymond91125** [comment]
There are a couple of pending RHEAs. What is the SOP? Should I wait and rerun checks? @hdrabkin Thanks.
RHEA:69172
RHEA:69176
RHEA:69332

**Comment by hdrabkin** [comment]
Hi @raymond91125 
We now have it set up that you can put the RHEAs in. The PR script will check that those RHEAs are not pubic yet, but will not fail the pull request; those will appear as warnings. Those RHEAs will NOT appear in the public files but will still appear in go-edit.obo. When the RHEA becomes public, the ids will show up in go, go-basic, etc.
Note, however: if you use a RHEA as a definition reference make sure there is also a PMID so the public definition will have a reference.

**Pull request closed without merging**
