### PR TITLE
Updated terms and relations as specified in the ticket #14582

### PR DESCRIPTION
**Pull request by BarbaraCzub**
Hi @ukemi @pgaudet @vanaukenk 
Could you please review before I merge?

The part that I felt less certain about, when I looked at the summary of changes below, was the "is_a: GO:0048856 ! anatomical structure development" in line(s) 147588-147587, but I have just had a look at this in Protégé, and it looks like this relationship has been inferred (and not asserted), so I suppose this is ok? 

Thanks,
Barbara

cc:
@RLovering 
@paolaroncaglia

### CODE REVIEW

**Comment by ukemi** [comment]
Looking at the structure of the ontology, it does look like cell projections are anatomical structures , with respect to their development, morphogenesis etc. What you have here is consistent with the axon representation. It's a shame that we can't look at the reasoned ontology in a pull request, but trying to do the reasoning in my head, this looks consistent to me.

**Comment by ukemi** [comment]
PS. I do think there might be something funny here though. It looks like in other areas, cellular component development terms are children of the organization terms. We might have to reexamine this area of the ontology. @vanaukenk would this be part of the work you have started?

**Comment by ukemi** [comment]
PPS. If the relationships is inferred, you can get rid of the asserted one.

**Comment by BarbaraCzub** [comment]
Hi @ukemi 
These terms have an 'organization' ancestry too:
screen shot 2017-12-22 at 13 12 27

**Comment by BarbaraCzub** [comment]
Hi @ukemi 

>PPS. If the relationships is inferred, you can get rid of the asserted one.

I initially (wrongly) thought this relationship was asserted, but when I checked in Protégé after having synchronized the reasoner, this relationship had the circle with the three horizontal lines inside it, so if I remember correctly, this means it is inferred? So, I'll leave it as it is.

**Comment by ukemi** [comment]
The circle and lines means the term has a logical definition. The yellow relationships are inferred.

**Comment by BarbaraCzub** [comment]
Hi @ukemi 

>Looking at the structure of the ontology, it does look like cell projections are anatomical structures , with respect to their development, morphogenesis etc. What you have here is consistent with the axon representation. It's a shame that we can't look at the reasoned ontology in a pull request, but trying to do the reasoning in my head, this looks consistent to me.

So (I infer) this comment means that it appears safe to merge these changes, and I should go ahead? Although I am not sure what you mean by the reasoned ontology (are you referring to the inferences that come up in Protégé after having synchronized the reasoner?).

**Comment by BarbaraCzub** [comment]
@ukemi 
> The circle and lines means the term has a logical definition. The yellow relationships are inferred.

Aren't they _all_ yellow?

**Comment by ukemi** [comment]
It might be easier to look together. Can you skype?

**Comment by BarbaraCzub** [comment]
Something went wrong. I thought maybe my ontology file version was out of date, so I tried 'git pull origin master' (details below), but this has not helped, because there is nothing new to commit.
@ukemi 

~/repos/go-ontology/src/ontology(issue-14582) $ git status
On branch issue-14582
nothing to commit, working tree clean
~/repos/go-ontology/src/ontology(issue-14582) $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/repos/go-ontology/src/ontology(master) $ git pull
Already up-to-date.
~/repos/go-ontology/src/ontology(master) $ git pull origin master
From https://github.com/geneontology/go-ontology
 * branch            master     -> FETCH_HEAD
Already up-to-date.
~/repos/go-ontology/src/ontology(master) $ git checkout issue-14582
Switched to branch 'issue-14582'
~/repos/go-ontology/src/ontology(issue-14582) $ git diff
~/repos/go-ontology/src/ontology(issue-14582) $ git commit -m 'Attempt2 after git pull orig mast #14582' go-edit.obo
On branch issue-14582
nothing to commit, working tree clean
~/repos/go-ontology/src/ontology(issue-14582) $ git pull origin master
From https://github.com/geneontology/go-ontology
 * branch            master     -> FETCH_HEAD
Already up-to-date.
~/repos/go-ontology/src/ontology(issue-14582) $ git checkout issue-14582
Already on 'issue-14582'
~/repos/go-ontology/src/ontology(issue-14582) $ git commit -m 'Attempt2 after git pull orig mast #14582' go-edit.obo
On branch issue-14582
nothing to commit, working tree clean
~/repos/go-ontology/src/ontology(issue-14582) $ git push origin issue-14582
Everything up-to-date
~/repos/go-ontology/src/ontology(issue-14582) $

**Comment by BarbaraCzub** [comment]
Success! Thank you for your help @ukemi =)

**Pull request merged**
