### PR TITLE
Added back RHEA. #25314

### PR DESCRIPTION
**Pull request by raymond91125**

### CODE REVIEW

**Comment by raymond91125** [comment]
@balhoff I don't understand this error,  could you help? Thanks.
FAIL Rule ../sparql/one-to-one-xrefs-by-subject-violation.sparql: 1 violation(s)
c,one_to_one_prefix
http://purl.obolibrary.org/obo/GO_0047751,RHEA:

**Comment by balhoff** [comment]
@raymond91125 the rule checks that there is not more than one exact RHEA xref for a given term. But looking at your diff, I don't see more than one, so I'm confused also.

**Comment by balhoff** [comment]
@raymond91125 I see the issue, we have an automatic migration of RHEA xrefs from obsolete terms to their replaced_by terms. So during the ontology build the xref from GO:0050213 gets moved to this term. If you think it makes sense, I would remove the RHEA xref from GO:0050213.

**Comment by raymond91125** [comment]
Ah, was wondering about that. Thanks.

**Pull request merged**
