### PR TITLE
fixing sparql query and using merge imports to get chebi, et al

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
@cmungall @pgaudet This fails because the sparql test now actually fails...so, my PR is working, but it won't pass travis ha.

**Comment by cmungall** [comment]
I repaired what I could using `robot repair` and references to obsolete classes for which chebi has provided a replaced_by, but they have not done that in all cases

**Comment by ukemi** [comment]
I just went through the errors in the Travis checks. It looks like all of the replacements went through following the alt identifiers. Should we change the names of the terms to reflect the updates in the new equivalence axioms and keep the old names as related synonyms? The last replacement is a bit questionable, but is a valid ChEBI identfier. I wonder if to follow GO rules we shouldn't use CHEBI:133476, which is the conjugate base of hydantoin-5-propionic acid. But looking at the current ontology, the checks should pass now.

**Comment by ukemi** [comment]
Getting better. The only two errors now are for GOCHE terms. I'm not sure how to fix them. 26619 is secondary to 25212 (metabolite) and 22582 is 33281 (antimicrobial agent). Looks like they are used in roles. Can you run robot to update that?

**Comment by dougli1sqrd** [comment]
I'm also getting other errors out of sparql_test though besides the obsolete links:
```
Rule /Users/edouglass/lbl/geneontology/go-ontology/src/sparql/equivalent-classes-violation.sparql: 5 violation(s)
baseClass,baseLabel,equivalentClass,equivalentLabel
http://purl.obolibrary.org/obo/CHEBI_18111,ribosomal RNA,http://purl.obolibrary.org/obo/SO_0000252,rRNA
http://purl.obolibrary.org/obo/CHEBI_17843,transfer RNA,http://purl.obolibrary.org/obo/SO_0000253,tRNA
http://purl.obolibrary.org/obo/BFO_0000023,role,http://purl.obolibrary.org/obo/CHEBI_50906,role
http://purl.obolibrary.org/obo/CHEBI_36080,protein,http://purl.obolibrary.org/obo/PR_000000001,protein
http://purl.obolibrary.org/obo/CHEBI_33699,messenger RNA,http://purl.obolibrary.org/obo/SO_0000234,mRNA

Rule /Users/edouglass/lbl/geneontology/go-ontology/src/sparql/owldef-self-reference-violation.sparql: 0 violation(s)

Rule /Users/edouglass/lbl/geneontology/go-ontology/src/sparql/trailing-whitespace-violation.sparql: 5 violation(s)
c,p,x
http://purl.obolibrary.org/obo/UBERON_4000164,http://purl.obolibrary.org/obo/IAO_0000115,The caudal fin is the most posterior median fin. It is composed of a complex of modified centra and modified neural and hemal arches and spines.
http://purl.obolibrary.org/obo/PO_0025026,http://www.geneontology.org/formats/oboInOwl#hasExactSynonym," 胚嚢細胞 (Japanese, exact)"
http://purl.obolibrary.org/obo/CL_0011108,http://purl.obolibrary.org/obo/IAO_0000115,Epithelial cell that is part of the colon epithelium.
http://purl.obolibrary.org/obo/RO_0002215,http://purl.obolibrary.org/obo/IAO_0000115,"A relation between a material entity (such as a cell) and a process, in which the material entity has the ability to carry out the process. "
http://purl.obolibrary.org/obo/CL_0000724,http://purl.obolibrary.org/obo/IAO_0000115, A differentiated cell that functions as a site of nitrogen fixation under aerobic conditions.

Rule /Users/edouglass/lbl/geneontology/go-ontology/src/sparql/obsolete-reference-violation.sparql: 2 violation(s)
goTerm,obsolete
http://purl.obolibrary.org/obo/GOCHE_26619,http://purl.obolibrary.org/obo/CHEBI_26619
http://purl.obolibrary.org/obo/GOCHE_22582,http://purl.obolibrary.org/obo/CHEBI_22582
```
There seem to be 5 equivalent class violations, and 5 trailing whitespace violations in addition to the remaining GOCHE obsolete link terms.

**Comment by cmungall** [comment]
Ah that's due to the merge of the imports closure. Some checks we want 
to run only on go, some we need to include the imports closure. awkward.

**Comment by dougli1sqrd** [comment]
I know my "fix" is a little silly, but it's not so bad. It works locally at least, we'll see what Travis says.

**Comment by pgaudet** [comment]
The two obsolete terms are not used in the ontology; they have been replaced by other terms but the old IDs are still in GO. What should we do ? @cmungall 
http://purl.obolibrary.org/obo/GOCHE_26619,http://purl.obolibrary.org/obo/CHEBI_26619
http://purl.obolibrary.org/obo/GOCHE_22582,http://purl.obolibrary.org/obo/CHEBI_22582

**Comment by dougli1sqrd** [comment]
So I've done some snooping, and it appears that GOCHE:26619 is defined on line 86675 in src/ontology/imports/chebi_import.owl. Similarly, GOCHE:22582 is defined on line 86196 of the same file. 

To fix this, would we just edit the these class definitions here?

**Comment by cmungall** [comment]
@pgaudet - I have looked over the PR, it all looks good, except for one thing

CHEBI have merged their 'secondary metabolite' term (http://purl.obolibrary.org/obo/CHEBI_26619) into 'metabolite' http://purl.obolibrary.org/obo/CHEBI_25212.

We use this in 3 places (click on 'files' above to see). As part of the repair, we are essentially changing the meaning of these 3 terms. This will give us non-valid inferences.

The simplest thing may be to remove the equivalence axioms for these 3 classes. We may potentially lose inferences, but it looks like we generally assert here (ugh)

Really CHEBI should not be merging classes that are not equivalent. They should be making obsolete IDs. This was a while ago, our goche was stale...

**Comment by cmungall** [comment]
OK, this is the reasoner diff, ignoring secondary metabolism inferences

```
[Term]
id: GO:0006843 ! mitochondrial citrate transmembrane transport
+is_a: GO:0006855 ! drug transmembrane transport

[Term]
id: GO:0006846 ! acetate transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0009751 ! response to salicylic acid
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0010034 ! response to acetate
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0010193 ! response to ozone
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0015123 ! acetate transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015137 ! citrate transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015244 ! fluconazole transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015306 ! sialate:cation symporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015499 ! formate transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015546 ! sulfathiazole transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015552 ! propionate transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015638 ! microcin transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0015724 ! formate transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015730 ! propanoate transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015746 ! citrate transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015894 ! acriflavine transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015900 ! benomyl transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015903 ! fluconazole transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0015906 ! sulfathiazole transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0018879 ! biphenyl metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0018919 ! gamma-1,2,3,4,5,6-hexachlorocyclohexane metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0018920 ! glyphosate metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0018922 ! iprodione metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0019415 ! acetate biosynthetic process from carbon monoxide
-is_a: GO:0017144 ! drug metabolic process

[Term]
id: GO:0019636 ! phosphonoacetate metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0022885 ! bacteriocin transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0030647 ! aminoglycoside antibiotic metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0035433 ! acetate transmembrane transport
+is_a: GO:0006855 ! drug transmembrane transport

[Term]
id: GO:0036272 ! response to gemcitabine
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0042212 ! cresol metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0042542 ! response to hydrogen peroxide
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0042889 ! 3-phenylpropionic acid transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0042890 ! 3-phenylpropionic acid transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0042919 ! benzoate transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0042925 ! benzoate transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:0043213 ! bacteriocin transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0043215 ! daunorubicin transport
-is_a: GO:0015893 ! drug transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0044597 ! daunorubicin metabolic process
-is_a: GO:0017144 ! drug metabolic process

[Term]
id: GO:0044598 ! doxorubicin metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:0045471 ! response to ethanol
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0046199 ! cresol catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:0046677 ! response to antibiotic
-is_a: GO:0050896 ! response to stimulus
+is_a: GO:0042221 ! response to chemical

[Term]
id: GO:0046679 ! response to streptomycin
-is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0060992 ! response to fungicide
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0061479 ! response to reverse transcriptase inhibitor
-is_a: GO:0042221 ! response to chemical
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0070301 ! cellular response to hydrogen peroxide
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0070980 ! biphenyl catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:0071311 ! cellular response to acetate
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071319 ! cellular response to benzoic acid
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071361 ! cellular response to ethanol
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071409 ! cellular response to cycloheximide
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071446 ! cellular response to salicylic acid stimulus
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071457 ! cellular response to ozone
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0071505 ! response to mycophenolic acid
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0071506 ! cellular response to mycophenolic acid
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072713 ! cellular response to thiabendazole
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072730 ! response to papulacandin B
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0072731 ! cellular response to papulacandin B
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072735 ! response to t-BOOH
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0072736 ! cellular response to t-BOOH
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072743 ! cellular response to erythromycin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072744 ! cellular response to trichodermin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072745 ! cellular response to antimycin A
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072746 ! cellular response to tetracycline
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072747 ! cellular response to chloramphenicol
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072750 ! cellular response to leptomycin B
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072752 ! cellular response to rapamycin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072755 ! cellular response to benomyl
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0072762 ! cellular response to carbendazim
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0080021 ! response to benzoic acid
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0080170 ! hydrogen peroxide transmembrane transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:0097307 ! response to farnesol
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0097308 ! cellular response to farnesol
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:0097330 ! response to 5-fluoro-2'-deoxyuridine
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:0097331 ! response to cytarabine
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1900321 ! regulation of maltotetraose transport
+is_a: GO:2001023 ! regulation of response to drug

[Term]
id: GO:1900322 ! negative regulation of maltotetraose transport
+is_a: GO:2001024 ! negative regulation of response to drug

[Term]
id: GO:1900323 ! positive regulation of maltotetraose transport
+is_a: GO:2001025 ! positive regulation of response to drug

[Term]
id: GO:1900753 ! doxorubicin transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:1900797 ! cordyol C metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1900798 ! cordyol C catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1900799 ! cordyol C biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901104 ! tetracenomycin C metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901105 ! tetracenomycin C catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901106 ! tetracenomycin C biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901107 ! granaticin metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901108 ! granaticin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901109 ! granaticin biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901110 ! actinorhodin metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901111 ! actinorhodin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901112 ! actinorhodin biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901114 ! erythromycin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901119 ! tobramycin metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901120 ! tobramycin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901121 ! tobramycin biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901122 ! bacitracin A metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901123 ! bacitracin A catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901124 ! bacitracin A biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901150 ! vistamycin metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901151 ! vistamycin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901152 ! vistamycin biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901153 ! paromomycin metabolic process
-is_a: GO:0017144 ! drug metabolic process

[Term]
id: GO:1901242 ! ATPase-coupled doxorubicin transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:1901322 ! response to chloramphenicol
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901323 ! response to erythromycin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901324 ! response to trichodermin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901325 ! response to antimycin A
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901326 ! response to tetracycline
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901344 ! response to leptomycin B
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901355 ! response to rapamycin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901425 ! response to formic acid
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1901479 ! benomyl transmembrane transporter activity
-is_a: GO:0015238 ! drug transmembrane transporter activity
+is_a: GO:0042895 ! antibiotic transmembrane transporter activity

[Term]
id: GO:1901709 ! (+)-larreatricin metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901728 ! monensin A metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901729 ! monensin A catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901730 ! monensin A biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901742 ! 2-deoxystreptamine metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901743 ! 2-deoxystreptamine catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901744 ! 2-deoxystreptamine biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901761 ! oxytetracycline metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1901762 ! oxytetracycline catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:1901763 ! oxytetracycline biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1901786 ! p-cresol biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1902130 ! (+)-lariciresinol metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:1902132 ! (+)-lariciresinol biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

[Term]
id: GO:1902349 ! response to chloroquine
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1902350 ! cellular response to chloroquine
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1902520 ! response to doxorubicin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1902522 ! response to 4'-epidoxorubicin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1903935 ! response to sodium arsenite
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1903936 ! cellular response to sodium arsenite
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1903967 ! response to micafungin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1903968 ! cellular response to micafungin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904309 ! response to cordycepin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904310 ! cellular response to cordycepin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904321 ! response to forskolin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904322 ! cellular response to forskolin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904404 ! response to formaldehyde
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904405 ! cellular response to formaldehyde
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904576 ! response to tunicamycin
-is_a: GO:0042221 ! response to chemical
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904577 ! cellular response to tunicamycin
-is_a: GO:0070887 ! cellular response to chemical stimulus
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904615 ! cellular response to biphenyl
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904643 ! response to curcumin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904644 ! cellular response to curcumin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1904975 ! response to bleomycin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1904976 ! cellular response to bleomycin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1905092 ! response to diosgenin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1905093 ! cellular response to diosgenin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1905235 ! response to quercetin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1905236 ! cellular response to quercetin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1905237 ! response to cyclosporin A
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1905238 ! cellular response to cyclosporin A
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1905307 ! response to miconazole
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1905308 ! cellular response to miconazole
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:1905794 ! response to puromycin
+is_a: GO:0046677 ! response to antibiotic

[Term]
id: GO:1905795 ! cellular response to puromycin
+is_a: GO:0071236 ! cellular response to antibiotic

[Term]
id: GO:2001099 ! maltotetraose transport
+is_a: GO:0042891 ! antibiotic transport

[Term]
id: GO:2001308 ! gliotoxin metabolic process
-is_a: GO:0017144 ! drug metabolic process
+is_a: GO:0016999 ! antibiotic metabolic process

[Term]
id: GO:2001309 ! gliotoxin catabolic process
+is_a: GO:0017001 ! antibiotic catabolic process

[Term]
id: GO:2001310 ! gliotoxin biosynthetic process
+is_a: GO:0017000 ! antibiotic biosynthetic process

```

There are 1400+ diffs when the erroneous secondary metabolism axioms are included

**Comment by cmungall** [comment]
Ticket on CHEBI tracker about ID merges: https://github.com/ebi-chebi/ChEBI/issues/3060#issuecomment-365120594

**Comment by ukemi** [comment]
I'm also a bit concerned still about reasoning over the roles. Acetate is an antibiotic. It seems like the roles are very narrow.

**Comment by cmungall** [comment]
What's the use case for pre-composed antibiotic terms in GO?

**Comment by ukemi** [comment]
I suspect it comes on the coat-tails of the drug terms. The response to terms are under discussion again, but the metabolism terms might be better discussed. Clearly in some bacteria, there iis an evolved response to metabolize antibiotics. If I recall correctly, the terms involving drugs and the like were going to remain as stubs and the actual chemicals were not going to be linked to them. The information would be captured in co-annotation when the context is correct. Perhaps in the GO-CAM world, we can revisit this strategy and make it even better. Leave all of the drug terms (if we decide to keep them) as stubs and use them in models when there is the proper role context. Something to propose in May?

**Pull request merged**
