### PR TITLE
new term GO:0180002 closes #24307

### LINKED ISSUE #24307: NTR: renal zinc excretion
For review https://github.com/geneontology/go-annotation/issues/4346

* **New term**
* renal zinc excretion

*is_a GO:0097254 renal tubular secretion

* **Definition (free text)**
The elimination of zinc ions from peritubular capillaries (or surrounding hemolymph in invertebrates) into the renal tubules to be incorporated subsequently into the urine.

* **Reference**
* PMID:28196538

* **Gene product name and ID to be annotated to this term**
* ZnT63C; FBgn0035432

### PR DESCRIPTION
**Pull request by ValWood**

### CODE REVIEW

**Comment by raymond91125** [comment]
The go-edit.obo file was corrupt. I tried to fix it. Please check to make sure your edits are preserved. @ValWood @edwong57 

git diff:
 [Term]
-<<<<<<< HEAD
 id: GO:0180002
 name: renal zinc excretion
 namespace: biological_process
@@ -454039,17 +454038,6 @@ is_a: GO:0097254 ! renal tubular secretion
 property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24307 xsd:anyURI
 created_by: vw
 creation_date: 2022-11-01T17:35:12Z
-=======
-id: GO:0170002
-name: halotropism
-namespace: biological_process
-def: "A sodium-specific negative tropism that is crucial for surviving and thriving under high salinity." [PMID:36243013]
-synonym: "root halotropism" EXACT []
-is_a: GO:0009606 ! tropism
-property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24300 xsd:anyURI
-created_by: ew
-creation_date: 2022-11-01T17:36:17Z
->>>>>>> 905e78f991a5a4bccaee5ea35a6b56c7a13b3dcf
 
 [Term]
 id: GO:0170002

**Comment by raymond91125** [comment]
It seems the go-edit.obo file is corrupt with git remnants. I tried to fix it and failed. There seems to be something else going on not obvious to me how to fix. @pgaudet

**Comment by ValWood** [comment]
@pgaudet  what do I need to do?

**Comment by raymond91125** [comment]
Jim fixed the file.

**Comment by ValWood** [comment]
Thanks @raymond91125 @balhoff  it isn't a good start that my first ontology commit caused a conflict!

**Pull request merged**
