### PR TITLE
Update ChEBI import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the ChEBI import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2022-01-12/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2022-01-12/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned.owl`

#### Added
- [ABC-type fatty-acyl-CoA transporter activity](http://purl.obolibrary.org/obo/GO_0015607) SubClassOf [ATPase-coupled lipid transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0034040) 

#### Added
- [S-nitrosoglutathione binding](http://purl.obolibrary.org/obo/GO_0035730) SubClassOf [anion binding](http://purl.obolibrary.org/obo/GO_0043168) 

#### Added
- [bile acid binding](http://purl.obolibrary.org/obo/GO_0032052) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [bile acid catabolic process](http://purl.obolibrary.org/obo/GO_0030573) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [bile acid secretion](http://purl.obolibrary.org/obo/GO_0032782) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [cellular response to prostaglandin stimulus](http://purl.obolibrary.org/obo/GO_0071379) SubClassOf [cellular response to lipid](http://purl.obolibrary.org/obo/GO_0071396) 

#### Added
- [diaminopimelate transport](http://purl.obolibrary.org/obo/GO_0015830) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Removed
- [fatty acid derivative binding](http://purl.obolibrary.org/obo/GO_1901567) SubClassOf [binding](http://purl.obolibrary.org/obo/GO_0005488) 

#### Added
- [fatty acid derivative binding](http://purl.obolibrary.org/obo/GO_1901567) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Removed
- [fatty acid derivative biosynthetic process](http://purl.obolibrary.org/obo/GO_1901570) SubClassOf [organic substance biosynthetic process](http://purl.obolibrary.org/obo/GO_1901576) 

#### Added
- [fatty acid derivative biosynthetic process](http://purl.obolibrary.org/obo/GO_1901570) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [fatty acid derivative catabolic process](http://purl.obolibrary.org/obo/GO_1901569) SubClassOf [organic substance catabolic process](http://purl.obolibrary.org/obo/GO_1901575) 

#### Added
- [fatty acid derivative catabolic process](http://purl.obolibrary.org/obo/GO_1901569) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [fatty acid derivative metabolic process](http://purl.obolibrary.org/obo/GO_1901568) SubClassOf [organic substance metabolic process](http://purl.obolibrary.org/obo/GO_0071704) 

#### Added
- [fatty acid derivative metabolic process](http://purl.obolibrary.org/obo/GO_1901568) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [fatty acid derivative transport](http://purl.obolibrary.org/obo/GO_1901571) SubClassOf [organic substance transport](http://purl.obolibrary.org/obo/GO_0071702) 

#### Added
- [fatty acid derivative transport](http://purl.obolibrary.org/obo/GO_1901571) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Removed
- [fatty acid primary amide biosynthetic process](http://purl.obolibrary.org/obo/GO_0062112) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [fatty acid primary amide catabolic process](http://purl.obolibrary.org/obo/GO_0062127) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [fatty acid primary amide metabolic process](http://purl.obolibrary.org/obo/GO_0062126) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [icosanoid binding](http://purl.obolibrary.org/obo/GO_0050542) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [icosanoid biosynthetic process](http://purl.obolibrary.org/obo/GO_0046456) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [icosanoid metabolic process](http://purl.obolibrary.org/obo/GO_0006690) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [icosanoid transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0071714) SubClassOf [lipid transporter activity](http://purl.obolibrary.org/obo/GO_0005319) 

#### Added
- [icosanoid transport](http://purl.obolibrary.org/obo/GO_0071715) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Removed
- [leukotriene A4 biosynthetic process](http://purl.obolibrary.org/obo/GO_1901753) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [leukotriene A4 catabolic process](http://purl.obolibrary.org/obo/GO_1901752) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [leukotriene A4 metabolic process](http://purl.obolibrary.org/obo/GO_1901751) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [leukotriene B4 biosynthetic process](http://purl.obolibrary.org/obo/GO_0097251) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [leukotriene B4 catabolic process](http://purl.obolibrary.org/obo/GO_0036101) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [leukotriene B4 metabolic process](http://purl.obolibrary.org/obo/GO_0036102) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [leukotriene catabolic process](http://purl.obolibrary.org/obo/GO_0036100) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [negative regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120190) SubClassOf [negative regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032369) 

#### Removed
- [negative regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905829) SubClassOf [negative regulation of catabolic process](http://purl.obolibrary.org/obo/GO_0009895) 

#### Added
- [negative regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905829) SubClassOf [negative regulation of lipid catabolic process](http://purl.obolibrary.org/obo/GO_0050995) 

#### Added
- [negative regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901414) SubClassOf [negative regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0045833) 

#### Removed
- [negative regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904277) SubClassOf [negative regulation of biosynthetic process](http://purl.obolibrary.org/obo/GO_0009890) 

#### Added
- [negative regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904277) SubClassOf [negative regulation of lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0051055) 

#### Removed
- [ochratoxin A biosynthetic process](http://purl.obolibrary.org/obo/GO_1900818) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [ochratoxin A catabolic process](http://purl.obolibrary.org/obo/GO_1900817) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [ochratoxin A metabolic process](http://purl.obolibrary.org/obo/GO_1900816) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [phosphatidylinositol-3,4-bisphosphate binding](http://purl.obolibrary.org/obo/GO_0043325) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [positive regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120189) SubClassOf [positive regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032370) 

#### Removed
- [positive regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905830) SubClassOf [positive regulation of catabolic process](http://purl.obolibrary.org/obo/GO_0009896) 

#### Added
- [positive regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905830) SubClassOf [positive regulation of lipid catabolic process](http://purl.obolibrary.org/obo/GO_0050996) 

#### Added
- [positive regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901415) SubClassOf [positive regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0045834) 

#### Removed
- [positive regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904278) SubClassOf [positive regulation of biosynthetic process](http://purl.obolibrary.org/obo/GO_0009891) 

#### Added
- [positive regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904278) SubClassOf [positive regulation of lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0046889) 

#### Removed
- [propionyl-CoA biosynthetic process](http://purl.obolibrary.org/obo/GO_1902860) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [propionyl-CoA catabolic process](http://purl.obolibrary.org/obo/GO_1902859) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [propionyl-CoA metabolic process](http://purl.obolibrary.org/obo/GO_1902858) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [prostaglandin transport](http://purl.obolibrary.org/obo/GO_0015732) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [protocatechuate catabolic process, ortho-cleavage](http://purl.obolibrary.org/obo/GO_0019618) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120188) SubClassOf [regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032368) 

#### Removed
- [regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905828) SubClassOf [regulation of catabolic process](http://purl.obolibrary.org/obo/GO_0009894) 

#### Added
- [regulation of prostaglandin catabolic process](http://purl.obolibrary.org/obo/GO_1905828) SubClassOf [regulation of lipid catabolic process](http://purl.obolibrary.org/obo/GO_0050994) 

#### Added
- [regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901413) SubClassOf [regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0019216) 

#### Removed
- [regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904276) SubClassOf [regulation of biosynthetic process](http://purl.obolibrary.org/obo/GO_0009889) 

#### Added
- [regulation of wax biosynthetic process](http://purl.obolibrary.org/obo/GO_1904276) SubClassOf [regulation of lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0046890) 

#### Added
- [response to prostaglandin](http://purl.obolibrary.org/obo/GO_0034694) SubClassOf [response to lipid](http://purl.obolibrary.org/obo/GO_0033993) 

#### Added
- [succinyl-CoA binding](http://purl.obolibrary.org/obo/GO_0120226) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [succinyl-CoA biosynthetic process](http://purl.obolibrary.org/obo/GO_1901290) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [succinyl-CoA catabolic process](http://purl.obolibrary.org/obo/GO_1901289) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [succinyl-CoA metabolic process](http://purl.obolibrary.org/obo/GO_0006104) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [thromboxane transport](http://purl.obolibrary.org/obo/GO_0071717) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869)

### CODE REVIEW

**Comment by pgaudet** [comment]
This is much better! ssuccinate and tyrosine are gone :) 
succinyl-coA is still there, I am not sure about that one. 

@hdrabkin @deustp01 Can you please have a look? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
@balhoff , I'd like to load the ontology file for this to see what the reasoner is using to create the succinyl-coA inferrence to lipd metabolic/catabolics.
Where does the file live?

**Comment by balhoff** [comment]
@hdrabkin I'll post an explanation here. You can also download this zip and open go-edit.obo from there: https://github.com/ontobot/go-ontology/archive/refs/heads/update-chebi-import-2022-01-12.zip

**Comment by balhoff** [comment]
@hdrabkin:

## [succinyl-CoA binding](http://purl.obolibrary.org/obo/GO_0120226) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) ##

  - [succinyl-CoA binding](http://purl.obolibrary.org/obo/GO_0120226) EquivalentTo [binding](http://purl.obolibrary.org/obo/GO_0005488) and ([has input](http://purl.obolibrary.org/obo/RO_0002233) some [succinyl-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_57292))
    - [succinyl-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_57292) SubClassOf [omega-carboxy-(fatty acyl)-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_177898)
      - [omega-carboxy-(fatty acyl)-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_177898) SubClassOf [lipid](http://purl.obolibrary.org/obo/CHEBI_18059)
  - [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) EquivalentTo [binding](http://purl.obolibrary.org/obo/GO_0005488) and ([has input](http://purl.obolibrary.org/obo/RO_0002233) some [lipid](http://purl.obolibrary.org/obo/CHEBI_18059))

**Comment by hdrabkin** [comment]
So basically, it looks like although the link between succinic acid and fatty acid may have been removed, the CoA adduct is being still being classified as an omega fatty acid CoA adduct.

**Comment by pgaudet** [comment]
@hdrabkin Do you want to contact ChEBI about this?

**Comment by hdrabkin** [comment]
@pgaudet , yes, I was planning to add this to the ticket I already submitted to them.

**Comment by deustp01** [comment]
A problem is that succinyl-CoA(5-) CHEBI:57292 (the predominant form of the molecule at pH 7.3) and succinyl-CoA CHEBI:15380 (the "charge-agnostic" form of the molecule) have entirely different parentages in the ontology:
Screen Shot 2022-01-13 at 10 46 16 AM
Screen Shot 2022-01-13 at 10 46 33 AM

**Comment by hdrabkin** [comment]
@deustp01 , so basically it looks like if they drop the link to omega carboxy-(fatty acyl)- we would be good?
Especially since it already has omega carboxyacyl-CoA parent.

**Comment by hdrabkin** [comment]
I'm wondering if it should be that the omega-carboxy-(fatty acyl)-CoA  term should be a child of the omega-carboxyacyl-CoA term

**Comment by deustp01** [comment]
> 

Maybe so. Right now succinyl-CoA(5-) only has charged parents and they connect directly or at one hop to "lipid". Would changing the ontology to replace  the charged version of omega-carboxy-(fatty acyl)-CoA with the uncharged one evade the link to "lipid"? It looks ot me like it would.
This ducks the whole issue of consistency in the ontology but would patch the specific problem here.

**Comment by hdrabkin** [comment]
I see that 

Incoming | ω-carboxy-(fatty acyl)-CoA(5−)  (CHEBI:177898)                                                                            is a   ω-carboxyacyl-CoA(5−) (CHEBI:133241)

Already

So basically need to know what is difference between an omega-carboxy-(fatty acyl) and an omega-carboxyacyl moiety. 
I can't find one. 
Since we've already established that succinate is not a fatty acid, I think I can request that this link be removed?

**Comment by deustp01** [comment]
Sue - ask for the deletion.

**Comment by ukemi** [comment]
But isn't there still the other path on the left of the bottom graph that @deustp01 shows above? I think he has hit thenail on the head in that the two ontology structures should be parallel.  So the charged one should follow the same path wrt the chemical structure as the top one.

**Comment by hdrabkin** [comment]
Chebi has fixed; however, the fix will be in the new release. 
Suggest we don't let it hold up our import; then re-import when new release happens?

**Comment by balhoff** [comment]
Closing; we have specified an older CHEBI version in #22734. Will wait for the next CHEBI release to fix the remaining issue.

**Pull request closed without merging**
