### PR TITLE
closes #26424

### LINKED ISSUE #26424: Suggested "do not annotate" terms
See
https://github.com/geneontology/go-annotation/issues/4115
Also GOC presentation. This is a selection of high-level terms used in annotation.
- [x] GO:0034641 cellular nitrogen compound metabolic process [56 direct annotation,  56 ARBA IEA,  0 EXP]
- [x] GO:0006807 nitrogen compound metabolic process [597 direct annotation, IEAs from InterPro, CGD, 97 PAINT IBA,  53 EXP]
- [x] GO:1901564 organonitrogen compound metabolic process [81 direct annotation,  All ARBA IEA]
- [x] GO:0044238 primary metabolic process  [241 direct annotation, 239 ARBA IEA, 2 EXP]
- [x] GO:0071704 organic substance metabolic process [231 direct annotation,  229 ARBA IEA,  2 EXP]
- [x] GO:0043170 macromolecule metabolic process [383 direct annotation,  377 IEA, 122 ARBA IEA,  3 EXP]
- [x] GO:0110165 cellular anatomical entity [1507 direct annotation,  1505 ARBA IEA,  EXP 2]
- [x] GO:0048588 developmental cell growth [70 direct annotation,  52 TAIR IEA,  7 EXP]
- [x] GO:0048856 anatomical structure development [2425 direct annotation,  719 ARBA IEA,   1673 PAINT IBA, 33 EXP]
- [ ] GO:0098771 inorganic ion homeostasis [87 direct annotation,  IEA TAIR 78, 1 EXP]
TAIR  from https://amigo.geneontology.org/amigo/reference/PMID:34562334 (these are predictions)
- [ ] GO:0060560 developmental growth involved in morphogenesis [74 direct annotation,  54 TAIR IEA,  8 EXP]
TAIR from https://amigo.geneontology.org/amigo/reference/PMID:34562334 (these are predictions)

[XXX direct annotation,  ARBA IEA,  EXP]

GO:0043231 intracellular membrane-bounded organelle HOLDING OFF ON THIS ONE HAS 14198 annotations 879 EXP, I wonder why??? 724 are HPA, are these useful? what does it mean?
10,794 are IBA?

- [x] GO:0043414 macromolecule methylation (2 direct) (already present)
- [x] changed "metabolic process" from "do not manually annotate" to "do not annotate"
- [x] GO:1901564 organonitrogen compound metabolic process [101, ARBA IEA]
- [x]  organonitrogen compound catabolic process [2 EXP]
- [x] organonitrogen compound biosynthetic  process [ 46 ALl IEA]
- [x] GO:0032879 regulation of localization [19 direct annotation,  4 EXP]

- [x] GO:0016310 phosphorylation AND ALL CHILDREN? (for now I did only the term)
- [x] GO:0016311 dephosphorylation AND ALL CHILDREN? (for now I did only the term)
- [x] GO:0046483   heterocycle metabolic process  [48 direct annotation,  7  EXP]

### PR DESCRIPTION
**Pull request by ValWood**

### CODE REVIEW

**Comment by ValWood** [comment]
@pgaudet do you know what 
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing file:/__w/go-ontology/go-ontology/src/ontology/go-edit-trimmed-imports.obo
is?

**Comment by balhoff** [comment]
Oh, you're getting that too?! It happened also in one of Pascale's PRs. I know the cause but I thought it was something she did on her branch. I'll look at the `master` branch.

**Comment by balhoff** [comment]
@ValWood once #26924 has been merged, then merge `master` into your branch.

**Comment by ValWood** [comment]
Thanks @balhoff !

**Comment by ValWood** [comment]
OK closing this!

**Pull request closed without merging**
