### PR TITLE
Update ChEBI import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the ChEBI import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-06-09/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-06-09/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned.owl`

#### Removed
- [2-aminoethylphosphonate binding](http://purl.obolibrary.org/obo/GO_0033226) SubClassOf [binding](http://purl.obolibrary.org/obo/GO_0005488) 

#### Added
- [2-aminoethylphosphonate binding](http://purl.obolibrary.org/obo/GO_0033226) SubClassOf [cation binding](http://purl.obolibrary.org/obo/GO_0043169) 

#### Removed
- [2-aminoethylphosphonate transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0033224) SubClassOf [active transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0022804) 

#### Added
- [2-aminoethylphosphonate transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0033224) SubClassOf [active ion transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0022853) 

- [2-aminoethylphosphonate transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0033224) SubClassOf [organic cation transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015101) 

#### Removed
- [2-aminoethylphosphonate transport](http://purl.obolibrary.org/obo/GO_0033223) SubClassOf [organic substance transport](http://purl.obolibrary.org/obo/GO_0071702) 

#### Added
- [2-aminoethylphosphonate transport](http://purl.obolibrary.org/obo/GO_0033223) SubClassOf [organic cation transport](http://purl.obolibrary.org/obo/GO_0015695) 

#### Added
- [21-deoxycortisol binding](http://purl.obolibrary.org/obo/GO_1903877) SubClassOf [alcohol binding](http://purl.obolibrary.org/obo/GO_0043178) 

#### Added
- [3-(2,3-dihydroxyphenyl)propanoate biosynthetic process](http://purl.obolibrary.org/obo/GO_1901792) SubClassOf [catechol-containing compound biosynthetic process](http://purl.obolibrary.org/obo/GO_0009713) 

#### Added
- [3-(2,3-dihydroxyphenyl)propanoate catabolic process](http://purl.obolibrary.org/obo/GO_1901791) SubClassOf [catechol-containing compound catabolic process](http://purl.obolibrary.org/obo/GO_0019614) 

#### Added
- [3-(2,3-dihydroxyphenyl)propanoate metabolic process](http://purl.obolibrary.org/obo/GO_1901790) SubClassOf [catechol-containing compound metabolic process](http://purl.obolibrary.org/obo/GO_0009712) 

#### Removed
- [ATPase-coupled 2-aminoethylphosphonate transporter activity](http://purl.obolibrary.org/obo/GO_0033225) SubClassOf [ATPase-coupled transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042626) 

#### Added
- [ATPase-coupled 2-aminoethylphosphonate transporter activity](http://purl.obolibrary.org/obo/GO_0033225) SubClassOf [ATPase-coupled ion transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042625) 

#### Added
- [ATPase-coupled ferric-enterobactin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015624) SubClassOf [lactone transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042971) 

#### Removed
- [CDP-diacylglycerol biosynthetic process](http://purl.obolibrary.org/obo/GO_0016024) SubClassOf [pyrimidine nucleotide biosynthetic process](http://purl.obolibrary.org/obo/GO_0006221) 

#### Removed
- [CDP-diacylglycerol catabolic process](http://purl.obolibrary.org/obo/GO_0046342) SubClassOf [pyrimidine nucleotide catabolic process](http://purl.obolibrary.org/obo/GO_0006244) 

#### Removed
- [CDP-diacylglycerol metabolic process](http://purl.obolibrary.org/obo/GO_0046341) SubClassOf [pyrimidine nucleotide metabolic process](http://purl.obolibrary.org/obo/GO_0006220) 

#### Added
- [FK506 binding](http://purl.obolibrary.org/obo/GO_0005528) SubClassOf [amide binding](http://purl.obolibrary.org/obo/GO_0033218) 

#### Added
- [N-acetylneuraminate biosynthetic process](http://purl.obolibrary.org/obo/GO_0046380) SubClassOf [amide biosynthetic process](http://purl.obolibrary.org/obo/GO_0043604) 

- [N-acetylneuraminate biosynthetic process](http://purl.obolibrary.org/obo/GO_0046380) SubClassOf [organonitrogen compound biosynthetic process](http://purl.obolibrary.org/obo/GO_1901566) 

#### Added
- [N-acetylneuraminate catabolic process](http://purl.obolibrary.org/obo/GO_0019262) SubClassOf [organonitrogen compound catabolic process](http://purl.obolibrary.org/obo/GO_1901565) 

#### Added
- [N-acetylneuraminate metabolic process](http://purl.obolibrary.org/obo/GO_0006054) SubClassOf [organonitrogen compound metabolic process](http://purl.obolibrary.org/obo/GO_1901564) 

- [N-acetylneuraminate metabolic process](http://purl.obolibrary.org/obo/GO_0006054) SubClassOf [cellular amide metabolic process](http://purl.obolibrary.org/obo/GO_0043603) 

#### Added
- [bile acid binding](http://purl.obolibrary.org/obo/GO_0032052) SubClassOf [steroid binding](http://purl.obolibrary.org/obo/GO_0005496) 

#### Added
- [bile acid catabolic process](http://purl.obolibrary.org/obo/GO_0030573) SubClassOf [steroid catabolic process](http://purl.obolibrary.org/obo/GO_0006706) 

#### Added
- [bile acid secretion](http://purl.obolibrary.org/obo/GO_0032782) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Removed
- [cellular response to 2-O-acetyl-1-O-hexadecyl-sn-glycero-3-phosphocholine](http://purl.obolibrary.org/obo/GO_1904317) SubClassOf [cellular response to oxygen-containing compound](http://purl.obolibrary.org/obo/GO_1901701) 

#### Added
- [cellular response to 2-O-acetyl-1-O-hexadecyl-sn-glycero-3-phosphocholine](http://purl.obolibrary.org/obo/GO_1904317) SubClassOf [cellular response to ether](http://purl.obolibrary.org/obo/GO_0071362) 

#### Removed
- [cellular response to antimycin A](http://purl.obolibrary.org/obo/GO_0072745) SubClassOf [cellular response to organonitrogen compound](http://purl.obolibrary.org/obo/GO_0071417) 

- [cellular response to antimycin A](http://purl.obolibrary.org/obo/GO_0072745) SubClassOf [cellular response to organic cyclic compound](http://purl.obolibrary.org/obo/GO_0071407) 

- [cellular response to antimycin A](http://purl.obolibrary.org/obo/GO_0072745) SubClassOf [cellular response to oxygen-containing compound](http://purl.obolibrary.org/obo/GO_1901701) 

#### Added
- [cellular response to antimycin A](http://purl.obolibrary.org/obo/GO_0072745) SubClassOf [cellular response to chemical stimulus](http://purl.obolibrary.org/obo/GO_0070887) 

#### Removed
- [chenodeoxycholic acid binding](http://purl.obolibrary.org/obo/GO_1902122) SubClassOf [steroid binding](http://purl.obolibrary.org/obo/GO_0005496) 

#### Added
- [chrysobactin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042933) SubClassOf [organic cation transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015101) 

#### Added
- [chrysobactin transport](http://purl.obolibrary.org/obo/GO_0042932) SubClassOf [organic cation transport](http://purl.obolibrary.org/obo/GO_0015695) 

#### Removed
- [enterobactin binding](http://purl.obolibrary.org/obo/GO_1903981) SubClassOf [organic cyclic compound binding](http://purl.obolibrary.org/obo/GO_0097159) 

- [enterobactin binding](http://purl.obolibrary.org/obo/GO_1903981) SubClassOf [heterocyclic compound binding](http://purl.obolibrary.org/obo/GO_1901363) 

#### Added
- [enterobactin binding](http://purl.obolibrary.org/obo/GO_1903981) SubClassOf [macrolide binding](http://purl.obolibrary.org/obo/GO_0005527) 

#### Removed
- [enterobactin biosynthetic process](http://purl.obolibrary.org/obo/GO_0009239) SubClassOf [heterocycle biosynthetic process](http://purl.obolibrary.org/obo/GO_0018130) 

#### Added
- [enterobactin biosynthetic process](http://purl.obolibrary.org/obo/GO_0009239) SubClassOf [macrolide biosynthetic process](http://purl.obolibrary.org/obo/GO_0033068) 

#### Removed
- [enterobactin catabolic process](http://purl.obolibrary.org/obo/GO_0046214) SubClassOf [heterocycle catabolic process](http://purl.obolibrary.org/obo/GO_0046700) 

#### Added
- [enterobactin catabolic process](http://purl.obolibrary.org/obo/GO_0046214) SubClassOf [polyketide catabolic process](http://purl.obolibrary.org/obo/GO_0030640) 

- [enterobactin catabolic process](http://purl.obolibrary.org/obo/GO_0046214) SubClassOf [lactone catabolic process](http://purl.obolibrary.org/obo/GO_1901335) 

#### Removed
- [enterobactin metabolic process](http://purl.obolibrary.org/obo/GO_0009238) SubClassOf [heterocycle metabolic process](http://purl.obolibrary.org/obo/GO_0046483) 

#### Added
- [enterobactin metabolic process](http://purl.obolibrary.org/obo/GO_0009238) SubClassOf [macrolide metabolic process](http://purl.obolibrary.org/obo/GO_0033067) 

#### Added
- [enterobactin transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042931) SubClassOf [lactone transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042971) 

#### Added
- [enterobactin transport](http://purl.obolibrary.org/obo/GO_0042930) SubClassOf [lactone transport](http://purl.obolibrary.org/obo/GO_0042969) 

#### Added
- [ferric enterobactin:proton symporter activity](http://purl.obolibrary.org/obo/GO_0015345) SubClassOf [lactone transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042971) 

#### Added
- [glucosylglycerol biosynthetic process](http://purl.obolibrary.org/obo/GO_0051473) SubClassOf [glycoside biosynthetic process](http://purl.obolibrary.org/obo/GO_0016138) 

#### Added
- [glucosylglycerol metabolic process](http://purl.obolibrary.org/obo/GO_0051472) SubClassOf [glycoside metabolic process](http://purl.obolibrary.org/obo/GO_0016137) 

#### Added
- [glucosylglycerol transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0051474) SubClassOf [carbohydrate derivative transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_1901505) 

#### Added
- [glucosylglycerol transport](http://purl.obolibrary.org/obo/GO_0051475) SubClassOf [glycoside transport](http://purl.obolibrary.org/obo/GO_1901656) 

#### Added
- [helvolic acid biosynthetic process](http://purl.obolibrary.org/obo/GO_1900812) SubClassOf [acetate ester biosynthetic process](http://purl.obolibrary.org/obo/GO_1900620) 

#### Added
- [helvolic acid metabolic process](http://purl.obolibrary.org/obo/GO_1900810) SubClassOf [acetate ester metabolic process](http://purl.obolibrary.org/obo/GO_1900619) 

#### Removed
- [lithocholic acid binding](http://purl.obolibrary.org/obo/GO_1902121) SubClassOf [steroid binding](http://purl.obolibrary.org/obo/GO_0005496) 

#### Added
- [negative regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120190) SubClassOf [negative regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032369) 

#### Added
- [platelet activating factor biosynthetic process](http://purl.obolibrary.org/obo/GO_0006663) SubClassOf [ether lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008611) 

#### Added
- [platelet activating factor catabolic process](http://purl.obolibrary.org/obo/GO_0062234) SubClassOf [glycerol ether catabolic process](http://purl.obolibrary.org/obo/GO_0044269) 

#### Added
- [platelet activating factor metabolic process](http://purl.obolibrary.org/obo/GO_0046469) SubClassOf [ether lipid metabolic process](http://purl.obolibrary.org/obo/GO_0046485) 

#### Added
- [positive regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120189) SubClassOf [positive regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032370) 

#### Added
- [regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120188) SubClassOf [regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032368) 

#### Removed
- [response to 2-O-acetyl-1-O-hexadecyl-sn-glycero-3-phosphocholine](http://purl.obolibrary.org/obo/GO_1904316) SubClassOf [response to oxygen-containing compound](http://purl.obolibrary.org/obo/GO_1901700) 

#### Added
- [response to 2-O-acetyl-1-O-hexadecyl-sn-glycero-3-phosphocholine](http://purl.obolibrary.org/obo/GO_1904316) SubClassOf [response to ether](http://purl.obolibrary.org/obo/GO_0045472) 

#### Removed
- [response to antimycin A](http://purl.obolibrary.org/obo/GO_1901325) SubClassOf [response to oxygen-containing compound](http://purl.obolibrary.org/obo/GO_1901700) 

- [response to antimycin A](http://purl.obolibrary.org/obo/GO_1901325) SubClassOf [response to organonitrogen compound](http://purl.obolibrary.org/obo/GO_0010243) 

- [response to antimycin A](http://purl.obolibrary.org/obo/GO_1901325) SubClassOf [response to organic cyclic compound](http://purl.obolibrary.org/obo/GO_0014070) 

#### Added
- [response to antimycin A](http://purl.obolibrary.org/obo/GO_1901325) SubClassOf [response to stimulus](http://purl.obolibrary.org/obo/GO_0050896) 

#### Removed
- [serotonin transport](http://purl.obolibrary.org/obo/GO_0006837) SubClassOf [cation transport](http://purl.obolibrary.org/obo/GO_0006812) 

#### Added
- [serotonin transport](http://purl.obolibrary.org/obo/GO_0006837) SubClassOf [organic cation transport](http://purl.obolibrary.org/obo/GO_0015695) 

#### Added
- [serotonin:sodium symporter activity](http://purl.obolibrary.org/obo/GO_0005335) SubClassOf [organic cation transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015101) 

#### Added
- [sialate:cation symporter activity](http://purl.obolibrary.org/obo/GO_0015306) SubClassOf [amide transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0042887) 

#### Added
- [suramin binding](http://purl.obolibrary.org/obo/GO_0043924) SubClassOf [amide binding](http://purl.obolibrary.org/obo/GO_0033218) 

#### Added
- [thienylcyclohexylpiperidine binding](http://purl.obolibrary.org/obo/GO_0016596) SubClassOf [cation binding](http://purl.obolibrary.org/obo/GO_0043169) 

#### Added
- [tyrosine:tyramine antiporter activity](http://purl.obolibrary.org/obo/GO_0070908) SubClassOf [organic cation transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015101)

### CODE REVIEW

**Comment by balhoff** [comment]
This is an update to the latest ChEBI release, now that we have removed role reasoning.

**Comment by hdrabkin** [comment]
These look ok to me.

**Review by krchristie — APPROVED** [review]
I think all of the additions are fine. Some of the removals are relations to less specific terms that are replaced with a slightly more specific term, so that's good.

Some of the removals might be worth looking into further. I'll put them in a comment on this ticket with some additional details. However, I don't think these issues should hold up proceeding with updating ChEBI.

**Comment by krchristie** [comment]
I think all of the additions are fine. Some of the removals are relations to less specific terms that are replaced with a slightly more specific term, so that's good.

Some of the removals might be worth looking into further. I'll put them in this ticket with some additional details. However, I don't think these issues should hold up proceeding with updating ChEBI.

**Comment by krchristie** [comment]
These are the three groups of removals that I think we might want to look at a little closer and see if we want them and need to see if we can get them back.

____

**_CDP-diacylglycerol terms - losing relationship to pyrimidine nucleotide_**

**CDP-diacylglycerol biosynthetic process** http://purl.obolibrary.org/obo/GO_0016024
Removed:
- CDP-diacylglycerol biosynthetic process SubClassOf pyrimidine nucleotide biosynthetic process

**CDP-diacylglycerol catabolic process** http://purl.obolibrary.org/obo/GO_0046342
Removed:
- CDP-diacylglycerol catabolic process SubClassOf pyrimidine nucleotide catabolic process

**CDP-diacylglycerol metabolic process** http://purl.obolibrary.org/obo/GO_0046341
Removed:
- CDP-diacylglycerol metabolic process SubClassOf pyrimidine nucleotide metabolic process

____

**_antimycin A terms - losing relationships to organonitrogen, organic cyclic, & oxygen-containing compounds_**

**cellular response to antimycin A** http://purl.obolibrary.org/obo/GO_0072745
Removed: 
- cellular response to antimycin A SubClassOf cellular response to organonitrogen compound
- cellular response to antimycin A SubClassOf cellular response to organic cyclic compound
- cellular response to antimycin A SubClassOf cellular response to oxygen-containing compound
Added
- cellular response to antimycin A SubClassOf cellular response to chemical stimulus

**response to antimycin A** http://purl.obolibrary.org/obo/GO_1901325
Removed
- response to antimycin A SubClassOf response to oxygen-containing compound
- response to antimycin A SubClassOf response to organonitrogen compound
- response to antimycin A SubClassOf response to organic cyclic compound
Added
- response to antimycin A SubClassOf response to stimulus

____

**_lithocholic acid term change_**

**lithocholic acid binding** http://purl.obolibrary.org/obo/GO_1902121
Removed
- lithocholic acid binding SubClassOf steroid binding

**Pull request merged**
