### PR TITLE
Removed synaptic vesicle recycling SubClassOf synaptic vesicle transp…

### PR DESCRIPTION
**Pull request by BarbaraCzub**
…ort to get rid of intracellular inference #14540 

Hi @pgaudet @vanaukenk @ukemi 

As @dosumis advised I removed the relation:
'synaptic vesicle recycling' SubClassOf 'synaptic vesicle transport'
in order to get rid of the following _inference_:
'synaptic vesicle endocytosis' SubClassOf 'intracellular transport'.

Could you please confirm whether I should go ahead and merge this?

Thank you,
Barbara

### CODE REVIEW

**Comment by ukemi** [comment]
Hi @BarbaraCzub 

It looks like the file is not is_a complete. You need to make an is_a parent for 'synaptic vesicle recycling', perhaps 'vesicle-mediated transport'.

-David

**Comment by dosumis** [comment]
> It looks like the file is not is_a complete. You need to make an is_a parent for 'synaptic vesicle recycling', perhaps 'vesicle-mediated transport'.

That would bring back the bad inference this edit was meant to remove.  You could put it directly under transport and add a has_participant some vesicle.

**Comment by BarbaraCzub** [comment]
Hi @ukemi and @dosumis 
Thanks for your comments. I've tried to do what @dosumis suggested to avoid the 'intracellular' inference.
screen shot 2017-12-06 at 10 51 20

However, one of the Travis checks has already failed again.

I noticed and clicked on the red triangle with the exclamation mark in Protégé (I am not sure whether this triangle is always there, or just now, because the reasoner found something wrong?).

One of the (reasonably informative) messages that get displayed is as follows:
screen shot 2017-12-06 at 10 50 07

I am not sure what to do to fix this. Perhaps I was supposed to add 'has participant' in a section other than SubClassOf?

**Comment by ukemi** [comment]
It looks like somehow you have lost a new term that was added to the ontology and also lost a merge. If you click on the details link next to the failed check and scroll all the way to the bottom of the report, you will see it in the report. It looks like there is also a bad syntax in some xrefs, but that doesn't cause things to fail ( I think those were mine). Let's bring that up on a call, because the warning wasn't obvious.

2017-12-06 10:58:45,504 WARN  (OBOFormatParser:1505) LINE: 477822 accepting bad xref with spaces:IntAct: EBI-16417801  LINE:
def: "A protein complex capable of activating an enzyme. Activating subunits may dissociate from the catalytic unit before the enzyme is active." [GOC:bhm, IntAct: EBI-16417801, PMID:16244137, PMID:28710280]
2017-12-06 10:58:45,507 WARN  (OBOFormatParser:1505) LINE: 477830 accepting bad xref with spaces:IntAct: EBI-16417801  LINE:
def: "A protein complex required for the activation of urease. Activator subunits dissociate before urease has catalytic function." [GOC:bhm, IntAct: EBI-16417801, PMID:16244137, PMID:28710280]
2017-12-06 10:58:57,470 WARN  (OBOFormatParser:1505) LINE: 484739 accepting bad xref with spaces:IntAct: EBI-16417801  LINE:
def: "A protein complex capable of activating an enzyme. Activating subunits may dissociate from the catalytic unit before the enzyme is active." [GOC:bhm, IntAct: EBI-16417801, PMID:16244137, PMID:28710280]
2017-12-06 10:58:57,470 WARN  (OBOFormatParser:1505) LINE: 484746 accepting bad xref with spaces:IntAct: EBI-16417801  LINE:
def: "A protein complex required for the activation of urease. Activator subunits dissociate before urease has catalytic function." [GOC:bhm, IntAct: EBI-16417801, PMID:16244137, PMID:28710280]
2017-12-06 10:59:04,948 ERROR (CommandRunner:5578) The verification failed with the following errors.
2017-12-06 10:59:04,949 ERROR (CommandRunner:5585) Missing ID: GO:0061957
2017-12-06 10:59:04,949 ERROR (CommandRunner:5591) Missing alternate ID: GO:0055098
2017-12-06 10:59:04,950 ERROR (CommandRunner:5591) Missing alternate ID: GO:0055099
make: *** [change-report.txt] Error 255

**Comment by BarbaraCzub** [comment]
Ok, thank you.

**Comment by ukemi** [comment]
I fixed the spaces.

**Pull request merged**
