### PR TITLE
Update Uberon import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the Uberon import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-07-03/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-uberon-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-07-03/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-uberon-import/go-ontology/src/ontology/reasoned.owl`

#### Added
- [dentin secretion](http://purl.obolibrary.org/obo/GO_0070468) SubClassOf [localization of cell](http://purl.obolibrary.org/obo/GO_0051674)

### CODE REVIEW

**Comment by balhoff** [comment]
@pgaudet is there any issue with the new inference `dentin secretion SubClassOf localization of cell`? Should we assign someone to this, or can I merge?

**Comment by pgaudet** [comment]
> is there any issue with the new inference dentin secretion SubClassOf localization of cell

This has been causing issues for a while, see also https://github.com/geneontology/go-ontology/issues/13396

Since 'dentin' is a tissue, perhaps secretion is not right ? Could it be merged into 'GO:0097187 dentinogenesis' ? 
@ukemi 
Looks like what is secreted are ECM proteins, see PMID:21196346

Thanks, Pascale

**Comment by ukemi** [comment]
Yes. What is secreted are ECM proteins, collagens and matrix proteins. It seems that the tissue contains a mineralized collagen matrix.

**Comment by ukemi** [comment]
I would suggest a rename of GO:0070468 to be dentin extracellular matrix secretion and then remove the logical def. Keep the asserted children.

**Comment by balhoff** [comment]
@pgaudet I chatted with @ukemi, and I will go ahead and merge this. Do you want to implement David's suggestion separately?

**Comment by pgaudet** [comment]
Hi Jim,

Yes I'll implement this separately ; should I not do this before you merge
this uberon update? Or is it completely independent?

Le mer. 12 août 2020 à 7:56 PM, Jim Balhoff <notifications@github.com> a
écrit :

**Comment by balhoff** [comment]
We can wait if you don't want to see the inference. You can just merge this after you're done, or let me know.

**Pull request merged**
