### PR TITLE
Update CL import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the CL import. Here's a diff of how this impacts the classified ontology:

Ontologies are identical

### CODE REVIEW

**Comment by balhoff** [comment]
@ukemi looks like the sperm cells are finally in here.

**Review by ukemi — COMMENTED** [review]
Looks like id: CL:1000451 might have gone missing and not been merged. I don't see it as a secondary identifier.

**Comment by balhoff** [comment]
It's in the main CL file (obsoleted). Do we need it in our import?

**Comment by ukemi** [comment]
Looks like we don't. It's usage is only in CL.

**Pull request merged**
