### PR TITLE
Update CL import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the CL import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-03-15/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-cl-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2020-03-15/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-cl-import/go-ontology/src/ontology/reasoned.owl`

#### Removed
- [T-helper 1 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035706) SubClassOf [helper T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035704) 

#### Added
- [T-helper 1 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035706) SubClassOf [T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0010818) 

#### Removed
- [T-helper 17 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035705) SubClassOf [helper T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035704) 

#### Added
- [T-helper 17 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035705) SubClassOf [T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0010818) 

#### Removed
- [T-helper 2 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035707) SubClassOf [helper T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035704) 

#### Added
- [T-helper 2 cell chemotaxis](http://purl.obolibrary.org/obo/GO_0035707) SubClassOf [T cell chemotaxis](http://purl.obolibrary.org/obo/GO_0010818) 

#### Removed
- [asymmetric neuroblast division](http://purl.obolibrary.org/obo/GO_0055059) SubClassOf [asymmetric stem cell division](http://purl.obolibrary.org/obo/GO_0098722) 

#### Added
- [asymmetric neuroblast division](http://purl.obolibrary.org/obo/GO_0055059) SubClassOf [asymmetric cell division](http://purl.obolibrary.org/obo/GO_0008356) 

#### Removed
- [auditory receptor cell development](http://purl.obolibrary.org/obo/GO_0060117) SubClassOf [columnar/cuboidal epithelial cell development](http://purl.obolibrary.org/obo/GO_0002066) 

#### Added
- [auditory receptor cell development](http://purl.obolibrary.org/obo/GO_0060117) SubClassOf [epithelial cell development](http://purl.obolibrary.org/obo/GO_0002064) 

#### Removed
- [cell cycle arrest of committed forebrain neuronal progenitor cell](http://purl.obolibrary.org/obo/GO_0021883) SubClassOf [regulation of stem cell division](http://purl.obolibrary.org/obo/GO_2000035) 

#### Removed
- [dendritic cell differentiation](http://purl.obolibrary.org/obo/GO_0097028) SubClassOf [leukocyte differentiation](http://purl.obolibrary.org/obo/GO_0002521) 

#### Added
- [dendritic cell differentiation](http://purl.obolibrary.org/obo/GO_0097028) SubClassOf [mononuclear cell differentiation](http://purl.obolibrary.org/obo/GO_1903131) 

#### Removed
- [dendritic cell migration](http://purl.obolibrary.org/obo/GO_0036336) SubClassOf [leukocyte migration](http://purl.obolibrary.org/obo/GO_0050900) 

#### Added
- [dendritic cell migration](http://purl.obolibrary.org/obo/GO_0036336) SubClassOf [mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071674) 

#### Removed
- [ganglion mother cell fate determination](http://purl.obolibrary.org/obo/GO_0007402) SubClassOf [stem cell fate determination](http://purl.obolibrary.org/obo/GO_0048867) 

#### Added
- [ganglion mother cell fate determination](http://purl.obolibrary.org/obo/GO_0007402) SubClassOf [cell fate determination](http://purl.obolibrary.org/obo/GO_0001709) 

#### Removed
- [inner ear auditory receptor cell differentiation](http://purl.obolibrary.org/obo/GO_0042491) SubClassOf [neuroepithelial cell differentiation](http://purl.obolibrary.org/obo/GO_0060563) 

#### Removed
- [lymphocyte differentiation](http://purl.obolibrary.org/obo/GO_0030098) SubClassOf [leukocyte differentiation](http://purl.obolibrary.org/obo/GO_0002521) 

#### Added
- [lymphocyte differentiation](http://purl.obolibrary.org/obo/GO_0030098) SubClassOf [mononuclear cell differentiation](http://purl.obolibrary.org/obo/GO_1903131) 

#### Removed
- [lymphocyte migration](http://purl.obolibrary.org/obo/GO_0072676) SubClassOf [leukocyte migration](http://purl.obolibrary.org/obo/GO_0050900) 

#### Added
- [lymphocyte migration](http://purl.obolibrary.org/obo/GO_0072676) SubClassOf [mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071674) 

#### Added
- [negative regulation of dendritic cell chemotaxis](http://purl.obolibrary.org/obo/GO_2000509) SubClassOf [negative regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071676) 

#### Removed
- [negative regulation of establishment or maintenance of neuroblast polarity](http://purl.obolibrary.org/obo/GO_2000248) SubClassOf [regulation of stem cell division](http://purl.obolibrary.org/obo/GO_2000035) 

#### Removed
- [negative regulation of inner ear auditory receptor cell differentiation](http://purl.obolibrary.org/obo/GO_0045608) SubClassOf [inhibition of neuroepithelial cell differentiation](http://purl.obolibrary.org/obo/GO_0002085) 

#### Removed
- [negative regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000402) SubClassOf [negative regulation of leukocyte migration](http://purl.obolibrary.org/obo/GO_0002686) 

#### Added
- [negative regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000402) SubClassOf [negative regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071676) 

#### Removed
- [negative regulation of neuroblast proliferation](http://purl.obolibrary.org/obo/GO_0007406) SubClassOf [negative regulation of stem cell proliferation](http://purl.obolibrary.org/obo/GO_2000647) 

#### Removed
- [neuroblast development](http://purl.obolibrary.org/obo/GO_0014019) SubClassOf [stem cell development](http://purl.obolibrary.org/obo/GO_0048864) 

#### Added
- [neuroblast development](http://purl.obolibrary.org/obo/GO_0014019) SubClassOf [cell development](http://purl.obolibrary.org/obo/GO_0048468) 

#### Removed
- [neuroblast differentiation](http://purl.obolibrary.org/obo/GO_0014016) SubClassOf [stem cell differentiation](http://purl.obolibrary.org/obo/GO_0048863) 

#### Added
- [neuroblast differentiation](http://purl.obolibrary.org/obo/GO_0014016) SubClassOf [cell differentiation](http://purl.obolibrary.org/obo/GO_0030154) 

#### Removed
- [neuroblast division](http://purl.obolibrary.org/obo/GO_0055057) SubClassOf [stem cell division](http://purl.obolibrary.org/obo/GO_0017145) 

#### Added
- [neuroblast division](http://purl.obolibrary.org/obo/GO_0055057) SubClassOf [cell division](http://purl.obolibrary.org/obo/GO_0051301) 

#### Removed
- [neuroblast fate commitment](http://purl.obolibrary.org/obo/GO_0014017) SubClassOf [stem cell fate commitment](http://purl.obolibrary.org/obo/GO_0048865) 

#### Added
- [neuroblast fate commitment](http://purl.obolibrary.org/obo/GO_0014017) SubClassOf [cell fate commitment](http://purl.obolibrary.org/obo/GO_0045165) 

#### Removed
- [neuroblast fate determination](http://purl.obolibrary.org/obo/GO_0007400) SubClassOf [stem cell fate determination](http://purl.obolibrary.org/obo/GO_0048867) 

#### Added
- [neuroblast fate determination](http://purl.obolibrary.org/obo/GO_0007400) SubClassOf [cell fate determination](http://purl.obolibrary.org/obo/GO_0001709) 

#### Removed
- [neuroblast fate specification](http://purl.obolibrary.org/obo/GO_0014018) SubClassOf [stem cell fate specification](http://purl.obolibrary.org/obo/GO_0048866) 

#### Added
- [neuroblast fate specification](http://purl.obolibrary.org/obo/GO_0014018) SubClassOf [cell fate specification](http://purl.obolibrary.org/obo/GO_0001708) 

#### Removed
- [neuroblast proliferation](http://purl.obolibrary.org/obo/GO_0007405) SubClassOf [stem cell proliferation](http://purl.obolibrary.org/obo/GO_0072089) 

#### Added
- [positive regulation of dendritic cell chemotaxis](http://purl.obolibrary.org/obo/GO_2000510) SubClassOf [positive regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071677) 

#### Removed
- [positive regulation of inner ear auditory receptor cell differentiation](http://purl.obolibrary.org/obo/GO_0045609) SubClassOf [positive regulation of neuroepithelial cell differentiation](http://purl.obolibrary.org/obo/GO_1902913) 

#### Removed
- [positive regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000403) SubClassOf [positive regulation of leukocyte migration](http://purl.obolibrary.org/obo/GO_0002687) 

#### Added
- [positive regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000403) SubClassOf [positive regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071677) 

#### Removed
- [positive regulation of neuroblast proliferation](http://purl.obolibrary.org/obo/GO_0002052) SubClassOf [positive regulation of stem cell proliferation](http://purl.obolibrary.org/obo/GO_2000648) 

#### Added
- [regulation of dendritic cell chemotaxis](http://purl.obolibrary.org/obo/GO_2000508) SubClassOf [regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071675) 

#### Removed
- [regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000401) SubClassOf [regulation of leukocyte migration](http://purl.obolibrary.org/obo/GO_0002685) 

#### Added
- [regulation of lymphocyte migration](http://purl.obolibrary.org/obo/GO_2000401) SubClassOf [regulation of mononuclear cell migration](http://purl.obolibrary.org/obo/GO_0071675) 

#### Removed
- [regulation of neuroblast proliferation](http://purl.obolibrary.org/obo/GO_1902692) SubClassOf [regulation of stem cell proliferation](http://purl.obolibrary.org/obo/GO_0072091)

### CODE REVIEW

**Comment by pgaudet** [comment]
@ukemi Those are the new inferences for changing GO:cell to CL:cell. Can you check to see if it looks OK to you ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Hmm. On first glance it looks like the neuroblast classification is inconsistent, I think this will need closer investigation. I am not the right person to look at the immune cell classification.

**Comment by pgaudet** [comment]
@addiehl if you have some time can you please look at this ?

**Comment by addiehl** [comment]
Are these changes to GO live in Amigo already?  It would be helpful for me to look at the big picture.

Also, do you want me to comment on whether I agree with the inferences?

Can't get to this until tomorrow morning due to meetings all afternoon today, but I will look then.

**Comment by pgaudet** [comment]
> Are these changes to GO live in Amigo already? It would be helpful for me to look at the big picture.

No, we don't want to commit until we are sure the inferences are correct. 

> Also, do you want me to comment on whether I agree with the inferences?

Yes, please

> Can't get to this until tomorrow morning due to meetings all afternoon today, but I will look then.

No rush at all.

**Comment by ukemi** [comment]
I have looked through the neuroblast/stem cell changes and they all seem to make sense with respect to the discussions we had with the CL group.

**Comment by balhoff** [comment]
I configured the makefile to use specific versions of external ontologies. I've set CL to a version from just before this change. I'll close this PR so we can pull in requested CL terms, and we can address migration to a newer CL release separately.

**Pull request closed without merging**
