### PR TITLE
Merged regulation of liquid surface tension into surfactant homeostas…

### PR DESCRIPTION
**Pull request by raymond91125**
…is. #24222

### CODE REVIEW

**Comment by raymond91125** [comment]
@balhoff CI failed twice, not sure why. Does it have something to do with the removal of dcterms:conformsTo? Thanks.

**Comment by balhoff** [comment]
@raymond91125 how did that happen that `go-pattern-conformance.ttl` was edited? It's autogenerated and shouldn't be changed manually.

**Comment by balhoff** [comment]
I guess merging terms results in some tricky Protege behavior with the external file. I would recommend just not committing any changes that appear in files outside of go-edit.obo. Could you redo the PR and not include the changes to that file?

**Comment by raymond91125** [comment]
I think protege did that. I was merging a regulation term into a 'non-regulation' term.

**Pull request closed without merging**
