### PR TITLE
closes #26796

### LINKED ISSUE #26796: Obsoletion request: GO:0000291   nuclear-transcribed mRNA catabolic process, exonucleolytic (and some descendants)
Please provide as much information as you can:

* **GO term ID and Label**

- [x] GO:0000291   nuclear-transcribed mRNA catabolic process, exonucleolytic
- [x] GO:0043928.  exonucleolytic catabolism of deadenylated mRNA
- [x] GO:0034428. nuclear-transcribed mRNA catabolic process, exonucleolytic, 5'-3'
- [x] GO:0070480  exonucleolytic nuclear-transcribed mRNA catabolic process involved in deadenylation-independent decay

* **Reason for deprecation** Put an x in the appropriate box: 
 

 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***

https://github.com/geneontology/go-annotation/issues/4966

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)

### PR DESCRIPTION
**Pull request by ValWood**

### CODE REVIEW

**Comment by ValWood** [comment]
Hi @balhoff  can you see the issue here, I did not see this before?
Thanks
Val

**Comment by ValWood** [comment]
I see what I did, I added changes on top of an existing branch. How do I fix that?

**Comment by ValWood** [comment]
Actually, I am in a new branch so I'm not sure what the problem is.

**Comment by balhoff** [comment]
@ValWood looks like you made some changes to GO:0070479, but that term had been since obsoleted on the master branch. If you tell me which of this content to keep, I can fix it for you:

```
[Term]
id: GO:0070479
name: obsolete nuclear-transcribed mRNA catabolic process, 5'-3' exonucleolytic nonsense-mediated decay
namespace: biological_process
<<<<<<< HEAD
def: "The chemical reactions and pathways resulting in the breakdown of the nuclear-transcribed mRNA transcript body of an mRNA in which an amino-acid codon has changed to a nonsense codon; occurs when the 5' end is not protected by a 5'-cap; degradation proceeds in the 5' to 3' direction." [PMID:18554525]
synonym: "5'-3' nonsense-mediated decay" EXACT [GOC:jp]
is_a: GO:0000184 ! nuclear-transcribed mRNA catabolic process, nonsense-mediated decay
=======
def: "OBSOLETE. The chemical reactions and pathways resulting in the breakdown of the nuclear-transcribed mRNA transcript body of an mRNA in which an amino-acid codon has changed to a nonsense codon; occurs when the 5' end is not protected by a 5'-cap; degradation proceeds in the 5' to 3' direction." [PMID:18554525]
comment: The reason for obsoletion is that this term was an unnecessary grouping term.
synonym: "5'-3' NMD" EXACT [GOC:jp]
synonym: "5'-3' nonsense-mediated decay" EXACT [GOC:jp]
synonym: "5'-3' nonsense-mediated mRNA decay" EXACT [GOC:jp]
synonym: "nuclear-transcribed mRNA breakdown, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]
synonym: "nuclear-transcribed mRNA catabolism, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]
synonym: "nuclear-transcribed mRNA degradation, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]
is_obsolete: true
replaced_by: GO:0000288
>>>>>>> master
```

**Comment by ValWood** [comment]
GO:0070479 shouldn't be obsoleted at the moment.

I  did obsolete a parent so it had to be rehoused. I'm not sure where i messed it up...

**Comment by balhoff** [comment]
It was obsoleted here: https://github.com/geneontology/go-ontology/pull/27225/files

If you just write out the full stanza how you want it to look in a comment here, I will fix the merge conflict.

**Comment by ValWood** [comment]
This should work

[Term]
id: GO:0070479
name: nuclear-transcribed mRNA catabolic process, 5'-3' exonucleolytic nonsense-mediated decay
namespace: biological_process
def: The chemical reactions and pathways resulting in the breakdown of the nuclear-transcribed mRNA transcript body of an mRNA in which an amino-acid codon has changed to a nonsense codon; occurs when the 5' end is not protected by a 5'-cap; degradation proceeds in the 5' to 3' direction." [PMID:18554525]
comment: The reason for obsoletion is that this term was an unnecessary grouping term.
synonym: "5'-3' NMD" EXACT [GOC:jp]
synonym: "5'-3' nonsense-mediated decay" EXACT [GOC:jp]
synonym: "5'-3' nonsense-mediated mRNA decay" EXACT [GOC:jp]
synonym: "nuclear-transcribed mRNA breakdown, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]
synonym: "nuclear-transcribed mRNA catabolism, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]
synonym: "nuclear-transcribed mRNA degradation, 5'-3' exonucleolytic nonsense-mediated decay" EXACT [GOC:mah]

**Comment by balhoff** [comment]
Thanks, this should be mergeable now, after the checks pass.

**Comment by balhoff** [comment]
@ValWood, oh you need to add an is_a parent. If you updated your branch from here you should be able to do that and push it back up.

**Comment by ValWood** [comment]
I'm a bit confused.
I did a git pull but I still can't  push:

error: failed to push some refs to 'https://github.com/geneontology/go-ontology.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I don't understand how it happened  though? The term  looked fine in my current copy (before and after I pulled)
 and my workflow looked normal , see below. So I can't figure out how I deleted it and got it back?

501  cd Desktop/Repos/go-ontology/
  502  pwd
  503  git pull
  504  git status
  505  git checkout -b vw-060302024-27171
  506  cd src/ontology/
  507  git diff
  508  git add go-edit.obo 
  509  git commit -m 'closes #27171'
  510  git status
  511  git push origin vw-060302024-27171

  512  git checkout master
  513  git pull
  514  git -d vw-060302024-27171
515  git pull
  516  git status
  518  git checkout -b vw-08-03-24-26796
  520  git diff
  521  git add go-edit.obo 
  522  git commit -m 'part #26796'
  523  git status
  524  git push origin  vw-08-03-24-26796

  527  git status
  528  git checkout master
  529  git pull
  530  git stash
  531  git checkout -b vw-08-03-24-26796-part2
  532  git diff
  533  git add go-edit.obo 
  534  git commit -m 'closes #26796'
  535  git status
  536  git push origin vw-08-03-24-26796-part2
  537  git status

I don't understand how the term was deleted when it was in my current copy. So confused!
Will you have time on Monday before or after the editors call to help me figure out what I did wrong?

**Pull request merged**
