### PR TITLE
Update taxon constraints

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the taxon constraints import. Here is a diff of how this impacts the classified ontology:

Ontologies are identical

### CODE REVIEW

**Comment by ValWood** [comment]
Are taxon constraints working now?

**Comment by balhoff** [comment]
@ValWood yes they should be. But they have been working fine as far as I know—was there a problem you're thinking of?

**Comment by ValWood** [comment]
I wasn't aware theat they were working, I thought we were still waiting from them to be reinstated.

I didn't see any in the logs yet but will double check with @ma

**Comment by balhoff** [comment]
Oh are you talking about annotation checks? I'm only thinking of the ontology.

**Comment by ValWood** [comment]
yep annotation checks. Are we still waiting on those being reinstated?

**Comment by dougli1sqrd** [comment]
So taxon checks are being worked on right now to get them out of the owltools check. Owltools does run the taxon checks, so you should see it in the group report at the end, but we're actively working on getting them in the standard reports.

**Comment by pgaudet** [comment]
@dougli1sqrd Are you sure the taxon reports are working ? 
I cannot find any file that shows errors for GO_AR:0000013
However I do see nucleus in bacteria in AmiGO (which should be forbidden), for example for Q8TIN4 (Methanosarcina acetivorans C2A); in which file should that be ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Well owltools won't filter anything, so you'll see taxon violations in amigo still. Otherwise owltools appears to be running (I see owltools output on latest snapshot) but not sure if that means owltools taxon checks are definitely working.

**Comment by pgaudet** [comment]
I do see some owltools output. I dont see any rule13 error. 
In which file should I see errors for Methanosarcina acetivorans C2A (TaxID:188937)?

**Pull request merged**
