### PR TITLE
Added the regulation term, still awaiting PMID ref

### PR DESCRIPTION
**Pull request by BarbaraCzub**
cc
@thomaspd 
@RLovering 

https://github.com/geneontology/synapse/issues/186

### CODE REVIEW

**Comment by BarbaraCzub** [comment]
Thanks @ukemi, I'll update the equivalence axiom as you advise.

@vanaukenk could you please update the GO Editors' Guide to reflect this change? 
The current instructions say 'biological regulation', not 'biological process': 
http://go-ontology.readthedocs.io/en/latest/NewRegTerm.html

Thank you,
Barbara

**Comment by ukemi** [comment]
Argh. You are right. I just checked the pattern.

**Comment by ukemi** [comment]
equivalentTo:
  text: "'biological regulation' and 'regulates' some %s"
  vars:
- entity

**Comment by BarbaraCzub** [comment]
So should I leave it as it is?

**Comment by ukemi** [comment]
Yup.

**Comment by BarbaraCzub** [comment]
ok. I'll merge then. Thank you!

**Comment by ukemi** [comment]
Sorry about that. I was pretty sure we had decided on biological process.

**Comment by BarbaraCzub** [comment]
No worries. Thank you for checking.

**Pull request merged**
