### PR TITLE
Removing redundant subclass assertions. 

### LINKED ISSUE #13275: removal of asserted regulates relationships
In discussion of the issue about the appropriate pattern for making regulation terms that was brought up in issue https://github.com/geneontology/go-ontology/issues/13252

we agreed that the directly asserted SubClass Of relationships of the form:
**regulates** some **'Kit signaling pathway'**

should be removed computationally for the many regulation terms where currently exist.

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #13275

### CODE REVIEW

**Comment by cmungall** [comment]
In the interests of transparency, this is the utterly evil script I used:

```
#!/usr/bin/perl

while(<>) {
    if (m@^relationship: (.*) \!@) {
        my $tuple = $1;
        if ($last =~ m@^intersection_of: (.*) \!@) {
            if ($1 eq $tuple) {
                next;
            }
        }
    }
    $last=$_;
    print;
}
```

I promise to do by scowl or something in future..

**Comment by cmungall** [comment]
to see the diff on the command line:

```
git diff origin/issue-13275
```

**Comment by pgaudet** [comment]
Hello,

I marked this editors-discussion because I'd like to know which redundant relations were removed, and which ones we should remove by hand (if any). 

Thanks, Pascale

**Comment by cmungall** [comment]
I re-ran this: #13397

**Comment by cmungall** [comment]
Random snippet:

```
[Term]
 id: GO:0002497
@@ -22269,7 +22097,6 @@ synonym: "B-cell deletion" EXACT []
 synonym: "B-lymphocyte deletion" EXACT []
 intersection_of: GO:0001783 ! B cell apoptotic process
 intersection_of: part_of GO:0002514 ! B cell tolerance induction
-relationship: part_of GO:0002514 ! B cell tolerance induction
 
 [Term]
 id: GO:0002517
@@ -22335,7 +22162,6 @@ synonym: "leukocyte trafficking during immune response" EXACT []
 is_a: GO:0002252 ! immune effector process
 intersection_of: GO:0050900 ! leukocyte migration
 intersection_of: part_of GO:0006955 ! immune response
-relationship: part_of GO:0006955 ! immune response
 
 [Term]
 id: GO:0002523
@@ -22350,7 +22176,6 @@ synonym: "leukocyte migration during inflammatory response" RELATED [GOC:dph
 synonym: "leukocyte trafficking during inflammatory response" RELATED []
 intersection_of: GO:0050900 ! leukocyte migration
 intersection_of: part_of GO:0006954 ! inflammatory response
-relationship: part_of GO:0006954 ! inflammatory response
````

**Pull request closed without merging**
