### PR TITLE
obsoleted 2 GO_REL fixes #17705

### LINKED ISSUE #17705: GO_REL: obsolete 'not_happens_during' and 'in_presence_of'
Hello, 

For the work on GO shapes (GO-CAM specifications) we are cleaning to GO_REL (hopefully rid of it completely; all useful relations should go in RO). 

For now I will obsolete 'not_happens_during' and 'in_presence_of'. These are not being used (see https://docs.google.com/spreadsheets/d/1zB8UKtG3JRGMkHgXmMpby-K5RFmYxGGRMEXULCCtcPo/edit#gid=0; existing annotations are being removed).

Thanks, Pascale

### PR DESCRIPTION
**Pull request by pgaudet**

### CODE REVIEW

**Comment by pgaudet** [comment]
Can someone check this PR ? There are many changes, possibly because this was not edited in Protege before ? 

@cmungall @ukemi 

Thanks, Pascale

**Comment by pgaudet** [comment]
@balhoff Do you think this is OK ?

**Review by balhoff — APPROVED** [review]
I think it looks okay.

**Comment by pgaudet** [comment]
yay !

**Comment by balhoff** [comment]
Sorry, I spoke too soon. Chatting with @pgaudet about whether gorel-edit should be edited instead.

**Pull request closed without merging**
