### PR TITLE
Added synonyms and regulation terms Fixes #14747

### LINKED ISSUE #14747: regulation of neuron projection arborization
I would like to see “regulation of neuron projection arborization” added as a child term of “neuron projection arborization” (GO:0140058).  Definition could be “Any process that modulates the frequency, rate or extent of the process in which the anatomical structures of a neuron projection are generated and organized into branches.” “positive…” and “negative…” children of “regulation of neuron projection arborization” are also needed. Synonyms: positive…, negative…, and regulation of neurite arborization.  Maybe “neuron projection branching” and “neurite branching” could be added as synonyms of “neuron projection arborization” (GO:0140058). PMID:17114044

### PR DESCRIPTION
**Pull request by BarbaraCzub**
@ukemi could you please review?

### CODE REVIEW

**Comment by ukemi** [comment]
Hi @BarbaraCzub ,

You should be able to create logical definitions for the positive and negative regulation terms as well as the core regulation term. See 'positive regulation of glucose import' and 'negative regulation of glucose import' as examples of the construction.

-D

**Comment by BarbaraCzub** [comment]
Hi @ukemi 

Thanks for pointing this out.

The checks passed.

In order to add the logical definitions now, should I merge this branch and close it, and then open a new branch to add these logical definitions? Or should I not merge this, and continue working on this branch?

Thanks,
Barbara


### Note re: GO Editors Guide
Perhaps the point about logical definitions should be clarified in the guidelines. Atm the '[Creating Regulation Terms](http://go-ontology.readthedocs.io/en/latest/NewRegTerm.html)' guide includes (among others) the following instructions:
- "To create a ‘positive regulation of x’ or ‘negative regulation of x’ term, the parent ‘regulation of x’ term must first be created. To create a parent regulation term: (...) ";
- "6. Create a logical definition for the term: biological_process and regulates some target process.";
- "7. Remove the asserted ‘biological regulation’ parent."
I followed these instructions to create the parent regulation term.

But then to create the positive and negative regulation child terms I followed the instructions in the '[Creating a New Ontology Term](http://go-ontology.readthedocs.io/en/latest/CreateNewTerm.html)' guide, because 'positive/negative regulation of a [process]' is an _is_a_ child of 'regulation of a [process]'. 

Or was I supposed to follow the instructions from 'Creating Regulation Terms' to create the positive/negative regulation terms, and the parentage would have been inferred by the reasoner?

(I do not remember how we did this back in October). 

cc @vanaukenk

**Comment by ukemi** [comment]
I would just finish the editing in this branch.

**Comment by ukemi** [comment]
@vanaukenk , do you want to modify the documentation together to get me up to speed on editing docs for the January meeting?

**Comment by BarbaraCzub** [comment]
Thanks @ukemi  

I am going this close this pull request then, because I will not be merging it.

**Comment by ukemi** [comment]
You can just commit back here to this branch and the pull request will update.

**Pull request merged**
