### PR TITLE
Fixing errors whereby some taxon constraints either lost their

### LINKED ISSUE #200: Error: "... OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI"
Hi.  We're using owltools v0.3.0 to extract a pombe-only subset of GO.

We're using this command line:

    owltools --use-catalog go-plus.owl --reasoner elk --make-species-subset \
         -t NCBITaxon:4896 -o -f obo go-plus-pombe-only.obo

in go-svn/ontology/extensions/

We get this error:

    Exception in thread "main" java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplString cannot be cast to org.semanticweb.owlapi.model.IRI
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.expand(MacroExpansionVisitor.java:162)
        at org.obolibrary.macro.MacroExpansionVisitor$MacroExpansions.<init>(MacroExpansionVisitor.java:122)
        at org.obolibrary.macro.MacroExpansionVisitor.expandAll(MacroExpansionVisitor.java:95)
        at owltools.mooncat.SpeciesSubsetterUtil.<init>(SpeciesSubsetterUtil.java:139)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:759)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)

Can you help?

Thanks.

### PR DESCRIPTION
**Pull request by cmungall**
IDs or were incorrectly entered in Protege.

Need to investigate why this wasn't caught earlier.
The OWL is valid (we use an AP for never-in), but not as intended.

This fixes the issue PomBase were having:
Fixes https://github.com/owlcollab/owltools/issues/200

### CODE REVIEW

**Comment by cmungall** [comment]
cc @ValWood @kimrutherford

**Comment by hdrabkin** [comment]
Do we need to re-evaluate the instructions in the documentation?

**Comment by ValWood** [comment]
Something is broken Harold;)

**Comment by hdrabkin** [comment]
Quickgo? 8)

**Comment by ValWood** [comment]
I think its "causally upstream" of QuickGO.

**Comment by ValWood** [comment]
Hi @cmungall 
Last week you said taxon restrictions were back:

I still don't see them in QuickGO?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009399#term=info

**Pull request merged**
