### PR TITLE
Added requested term Fixes geneontology/synapse#206

### PR DESCRIPTION
**Pull request by BarbaraCzub**
cc
@thomaspd 
@RLovering

### CODE REVIEW

**Review by ukemi — COMMENTED** [review]
I'm not sure the has_part 'x cell' relationships are appropriate. Does the synapse have_part the whole cell? Is this a pattern that you got from other terms?

**Comment by BarbaraCzub** [comment]
Hm... No, it is not the whole cell. So, what should the relationship be? 'Overlaps'?

**Comment by BarbaraCzub** [comment]
And can I use 'overlaps' in a logical definition, or should I add these relationships in the 'SubClass Of' field instead?

**Comment by ukemi** [comment]
Are there any other examples that are already in place?

**Pull request merged**
