### PR TITLE
Issue 14540

### PR DESCRIPTION
**Pull request by BarbaraCzub**
Hi @pgaudet and @vanaukenk 

I have update the definition of the parent term 'synaptic vesicle endocytosis' and added the child terms: 

+id: GO:0150007
+name: clathrin-dependent synaptic vesicle endocytosis
and
+id: GO:0150008
+name: bulk synaptic vesicle endocytosis

Could you please review before I merge?

Thank you,
Barbara

### CODE REVIEW

**Comment by BarbaraCzub** [comment]
One of the Travis checks failed.

The red line in the details says: 'The command "cd src/ontology && make travis_test" exited with 2.'

What does this mean? How do I fix this? @cmungall are you able to help?

Thanks,
Barbara

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 
It's because your version is out of synch with master in a way that causes problems. 

You need to do: 
> git checkout yourbranch
> git pull origin master 
> fix any conflicts
> commit 
> push again 

Skype me if you have issues. 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 
Thanks for your help.

I have just done what you suggested, i.e. typed in the command highlighted in the screenshot below. (I admit I did not do this previously, as the instructions suggest this is optional).
screen shot 2017-12-01 at 13 53 22

But then this message popped up on my terminal:
screen shot 2017-12-01 at 13 54 59

And I have no idea what to do now... any suggestions?

Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 
This all workout out ok now. Thank you again for your help.
I'll merge now.
Thanks,
Barbara

**Comment by BarbaraCzub** [comment]
Just to confirm, I am not deleting this branch yet, because there are other points in this issue https://github.com/geneontology/go-ontology/issues/14540 which I still need to address. 
E.g. getting rid of the 'intracellular transport' inference.

**Comment by pgaudet** [comment]
Hi @BarbaraCzub 
It's OK to leave the ticket open, but you should delete the branch - or at any rate, start from a new branch when you start working on the next changes. 

That will avoid conflict/merge problems in the future. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello again @BarbaraCzub 
The command 'pull origin master' is optional (and in fact best avoided, because it can lead to useless conflicts in the file). 

However the Travis error you got was caused by (1) new terms and (2) a new alt_id (ie, a merge). 
This needs to be fixed by pulling master into your branch as indicated above. 

We need documentation about this, but this should go in a separate section ("Arghhh"?) about travail fails and how to fix them. 

Pascale

**Comment by BarbaraCzub** [comment]
Ok, I'm deleting this branch then. Thanks.

**Pull request merged**
