### PR TITLE
refined relations between endocytic process terms and added PMIDs whe…

### PR DESCRIPTION
**Pull request by BarbaraCzub**
…re they were missing #16547

cc @RLovering

### CODE REVIEW

**Review by ukemi — COMMENTED** [review]
Hi,

Have another look at GO:0098881. I don't think there should be two genuses in the logical definition. Seems like there is an error.

**Comment by BarbaraCzub** [comment]
Thanks @ukemi 
I included both terms in the logical definition, because the process of 'exocytic insertion of neurotransmitter receptor to plasma membrane' involves both 'vesicle docking' and 'vesicle tethering'. But perhaps I should remove the logical definition all together then, and manually assert the relationships with these parent terms?
Thanks,
Barbara

**Comment by ukemi** [comment]
Yes. That makes more sense to me.

**Comment by BarbaraCzub** [comment]
Ok. Thanks. I'll remove the logical definitions and assert parents manually.

**Pull request merged**
