### PR TITLE
Refresh chebi ph 7.3 mapping.

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by balhoff** [comment]
QC failed with inferred equivalences:

```
ERROR Equivalence: <http://purl.obolibrary.org/obo/GO_0015913> == <http://purl.obolibrary.org/obo/GO_0015912>
ERROR Equivalence: <http://purl.obolibrary.org/obo/GO_1904517> == <http://purl.obolibrary.org/obo/GO_0005524>
ERROR Equivalence: <http://purl.obolibrary.org/obo/GO_1904608> == <http://purl.obolibrary.org/obo/GO_1902065>
ERROR Equivalence: <http://purl.obolibrary.org/obo/GO_1904609> == <http://purl.obolibrary.org/obo/GO_1905232>
```

**Comment by pgaudet** [comment]
I dont understand this one: 

> ERROR Equivalence: <http://purl.obolibrary.org/obo/GO_1904608> == <http://purl.obolibrary.org/obo/GO_1902065>

ChEBI has: 
monosodium L-glutamate ([CHEBI:64243](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A64243)) has part L-glutamate(1−) ([CHEBI:29985](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A29985))


I suppose we asserted somewhere else that these two compounds are equivalent ?

**Comment by deustp01** [comment]
> ChEBI has: monosodium L-glutamate ([CHEBI:64243](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A64243)) has part L-glutamate(1−) ([CHEBI:29985](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A29985))
> 
> I suppose we asserted somewhere else that these two compounds are equivalent ?

Trying to remember introductory chemistry here, but I think it makes sense to say that monosodium L-glutamate ([CHEBI:64243] has two parts, actually, one L-glutamate(1−) ([CHEBI:29985] plus one sodium(1+) ([CHEBI:29101](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A29101)), which also makes monosodium L-glutamate an instance of sodium salt ([CHEBI:26714](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A26714))

**Comment by pgaudet** [comment]
Thanks @deustp01 

This equivalence is also a bit odd to me too, but they are calculated to be equivalent according to the GCI patterns (@balhoff can probably explain better). So we need to merge (obsolete/replace) the monosodium terms. If this information is important it will need to be captured in an extension. 

Thanks, Pascale

**Comment by deustp01** [comment]
@ukemi does this jog any amino acid GCI memories? Or were salts of amino acids not considered as they would dissociate to the free amino acid ion and atomic counterion in a physiological environment and therefore be out of scope for GO annotations?

**Comment by ukemi** [comment]
Nothing pops out at me, but I tend to think that is isn't restricted to amino acids since it appears that the Mg-ATP had the same issue, didn't it?

**Comment by pgaudet** [comment]
response to monosodium glutamate: https://github.com/geneontology/go-ontology/issues/24592

**Comment by balhoff** [comment]
@pgaudet it got a little further, but now we've got issues with cases where we haven't used the pH 7.3 form:

```
ERROR: CHEBI IDs should be mapped to pH 7.3:
CHEBI:10003
CHEBI:131429
CHEBI:15705
CHEBI:15750
CHEBI:15904
CHEBI:16110
CHEBI:16214
CHEBI:16900
CHEBI:17984
CHEBI:18230
CHEBI:18250
CHEBI:18296
CHEBI:18376
CHEBI:21397
CHEBI:25168
CHEBI:26666
CHEBI:28494
CHEBI:28599
CHEBI:28815
CHEBI:33184
CHEBI:33575
CHEBI:33704
CHEBI:35340
CHEBI:35366
CHEBI:37554
CHEBI:383703
CHEBI:59814
CHEBI:60245
CHEBI:60562
CHEBI:60579
CHEBI:61006
CHEBI:61057
CHEBI:71353
CHEBI:73204
CHEBI:8984
```

**Comment by balhoff** [comment]
I might be able to fix all those but I worry about missing some chemical nuance.

**Comment by pgaudet** [comment]
Here's the mapping


CHEBI:10003 CHEBI:65028 ribostamycin sulfate
CHEBI:131429 CHEBI:192797 carcinine
CHEBI:15705 CHEBI:59869 L-α-amino acid
CHEBI:15750 CHEBI:57497 dolichyl diphosphate
CHEBI:15904 CHEBI:17176 long-chain fatty acid
CHEBI:16110 CHEBI:57643 1,2-diacyl-sn-glycero-3-phosphocholine(1+)
CHEBI:16214 CHEBI:57683 dolichyl phosphate
CHEBI:16900 CHEBI:83348 chlorophyllide a
CHEBI:17984 CHEBI:57288 acyl-CoA
CHEBI:18230 CHEBI:58416 chlorophyll a
CHEBI:18250 CHEBI:58422 chondroitin 4'-sulfate
CHEBI:18296 CHEBI:62065 chondroitin 6'-sulfate
CHEBI:18376 CHEBI:58465 dermatan sulfate 
CHEBI:21397 CHEBI:37547 L-altrarate(1−)
CHEBI:25168 CHEBI:64997 mannosylinositol phosphorylceramide
CHEBI:26666 CHEBI:58951 short-chain fatty acid
CHEBI:28494 CHEBI:62237 cardiolipin
CHEBI:28599 CHEBI:60052 siroheme
CHEBI:28815 CHEBI:157750 heparan sulfate
CHEBI:33184 CHEBI:83139 long-chain fatty acyl-CoA
CHEBI:33575 CHEBI:29067 carboxylic acid
CHEBI:33704 CHEBI:78608 α-amino acid
CHEBI:35340 Remove?? this is not physiological 
CHEBI:35366 CHEBI:28868 fatty acid
CHEBI:37554 CHEBI:77636 fatty acyl-CoA
CHEBI:383703 Remove?? this is not physiological 
CHEBI:59814 CHEBI:59869 L-α-amino acid anion
CHEBI:60245 CHEBI:64916 inositol phosphoceramide
CHEBI:60562 CHEBI:61717 ferroheme c(2−)
CHEBI:60579 CHEBI:30623 oxalate(2-)
CHEBI:61006 CHEBI:74997 mannosyl diphosphorylinositol ceramide
CHEBI:61057 Remove?? this is not physiological 
CHEBI:71353 CHEBI:71308 Mo(VI)-molybdopterin cytosine dinucleotide
CHEBI:73204 CHEBI:73202 ceramide phosphoethanolamine
CHEBI:8984 CHEBI:23872 dodecyl sulfate Remove?? this is not physiological

There are 3 for which I dont find a 7.3 form: CHEBI:35340, CHEBI:383703 and CHEBI:61057

I dont see that these are used in the ontology; can we remove them? 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet there are a few discrepancies in your list compared to the mappings from Rhea: https://raw.githubusercontent.com/geneontology/go-ontology/4f992f098d671315b2c24c298b86bbec4dc2d4f0/src/biochebi/chebi_pH7_3_mapping.tsv (like acyl-CoA vs acetyl-Coa).

Not sure if I should just go with the mappings from Rhea, or if there was some biochemistry knowledge I need to employ.

**Comment by pgaudet** [comment]
You can replace acylCoA CHEBI:17984 by CHEBI:58342

What other ones are not matching?

**Comment by balhoff** [comment]
Another one: CHEBI:15904 (long-chain fatty acid) to CHEBI:17176 -> Rhea has CHEBI:57560

**Comment by pgaudet** [comment]
CHEBI:15904 CHEBI:57560

**Pull request merged**
