### PR TITLE
Update RO import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the RO import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2019-11-22/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-ro-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2019-11-22/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-ro-import/go-ontology/src/ontology/reasoned.owl`

#### Added
- AnnotationProperty: [IAO_0000589](http://purl.obolibrary.org/obo/IAO_0000589) 

#### Added
- [L-cysteine catabolic process via cystine](http://purl.obolibrary.org/obo/GO_0019453) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [L-methionine biosynthetic process from homoserine via O-phospho-L-homoserine and cystathionine](http://purl.obolibrary.org/obo/GO_0033516) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [beta-alanine biosynthetic process via 3-ureidopropionate](http://purl.obolibrary.org/obo/GO_0033396) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [cysteine biosynthetic process via S-sulfo-L-cysteine](http://purl.obolibrary.org/obo/GO_0019345) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [lysine biosynthetic process via alpha-aminoadipate and N2-acetyl-alpha-aminoadipate](http://purl.obolibrary.org/obo/GO_0051976) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [lysine biosynthetic process via alpha-aminoadipate and saccharopine](http://purl.obolibrary.org/obo/GO_0051975) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575) 

#### Added
- [lysine biosynthetic process via diaminopimelate and L-2-acetamido-6-oxoheptanedioate](http://purl.obolibrary.org/obo/GO_0033360) SubClassOf [cellular modified amino acid metabolic process](http://purl.obolibrary.org/obo/GO_0006575)

### CODE REVIEW

**Comment by balhoff** [comment]
@ukemi @vanaukenk did we expect to get these new inferences from the RO update? Do they relate to `has_intermediate`?

**Comment by vanaukenk** [comment]
@balhoff - 'has intermediate' seems the likely suspect, but I can't trace yet how the inference is actually being made.

**Comment by ukemi** [comment]
Yes. has_intermediate is suspect here. It should not be a child of has_primary_input_or_output. It should be a child of has_participant. We decided that we would reserve the classification of metabolic pathways to biosynthesis and catabolism of primary inputs and outputs. If we want to include intermediates at some point, I think we should invoke a primary participant. Otherwise we are going to get all kinds of stuff that really isn't very informative.

**Comment by ukemi** [comment]
@balhoff points out that my hypothesis is incorrect. I will have to look more closely at this tomorrow.Any way we can get the inference explanation on these? I suspect somewhere we forgot to change a relation or a property chain.

**Comment by ukemi** [comment]
Should be fixed in #18383

**Comment by ukemi** [comment]
@balhoff I tried to checkout this branch locally to run it in Protege and see the inference explanation, but for some reason git would not recognize the branch. Remind me to have you show me how to do that and I will add it to the documentation.

**Comment by ukemi** [comment]
@vanaukenk  the key here was to go straight to the inferred genus. Since all the incorrect classifications were to the same super-class, it was the likely culprit.

**Pull request merged**
