### PR TITLE
3 new terms for anastomosis during sprouting angiogenesis, fixes #13690

### LINKED ISSUE #13690: NTR vascular anastomosis
PMID: 	28264837 

NTR vascular anastomosis- The connection of angiogenic sprouts to another vessel or sprout during the formation of vascular networks by sprouting angiogenesis.
PMID: 	28264837 
part of  GO:0002040 sprouting angiogenesis
NTR vascular anastomosis has_part 
NTR cell adhesion involved in vascular anastomosis - The attachment of a cell, either to another cell or to an underlying substrate such as the extracellular matrix, via cell adhesion molecules that contributes to the formation of a vascular network.
is_a 	GO:0007155 cell adhesion

NTR vascular anastomosis has_part 
NTR 	endothelial tip cell filopodium assembly-The assembly of a filopodium, a thin, stiff protrusion extended by the endothelial tip cell of a vascular sprout.
is_a GO:0046847 filopodium assembly

### PR DESCRIPTION
**Pull request by krchristie**

### CODE REVIEW

**Comment by cmungall** [comment]
OWLAPI parse errors are incredibly hard to read...

We'll look into making these more targeted but in the interim the protocol is to find the part of the report that says `OBOFormatOWLAPIParser`

like here:

```
--------------------------------------------------------------------------------
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@2c3dec30
    Stack trace:
LINENO: 475107 - Unexpected tag id in term frame.
LINE: id: GO:0120079        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
```

ok so we found the message but I have no idea why it's complaining since 'id' is obviously valid

**Comment by cmungall** [comment]
Ah, something odd has gone wrong with how the new terms were inserted into the file, creating stanzas without a `[Term]` header. I have never seen this before in many many git commits, very odd..... will look further

**Comment by krchristie** [comment]
I was working on this in a different branch that I started last week, but when the pull request for that one indicated conflicts. Looks like I made a mistake when I resolved the conflicts. Thanks for finding that.

**Comment by cmungall** [comment]
OK, that's good to know, @kltm were trying to figure the different ways this could happen with a normal commit!

**Pull request merged**
