### PR TITLE
Added chloroplast to plant slim. Fixes #16494

### LINKED ISSUE #16494: add chloroplast to Plant GO slim
@tberardini and I were discussing including chloroplast (GO:0009507)
in the plant go slim.
there is of course a thylakoid term (part of a chloroplast) and a plastid term but arguably folks would be interested in this specific magical organelle.

### PR DESCRIPTION
**Pull request by tberardini**

### CODE REVIEW

**Comment by tberardini** [comment]
Not proceeding beyond here today. This was the diff:

@@ -112169,6 +112169,7 @@ id: GO:0009507
 name: chloroplast
 namespace: cellular_component
 def: "A chlorophyll-containing plastid with thylakoids organized into grana and frets, or stroma thylakoids, and embedded in a stroma." [ISBN:0471245208]
+subset: goslim_plant
 xref: Wikipedia:Chloroplast
 is_a: GO:0009536 ! plastid
 relationship: never_in_taxon NCBITaxon:28009 {source="PMID:21311032"} ! Choanoflagellida

**Comment by ukemi** [comment]
Looks like a pipeline issue. It seems that there is a file subsets/*.owl that can't be located. @dougli1sqrd or @balhoff do you know why this file is being called? Is there something new in the build protocol?

**Comment by ukemi** [comment]
Also looks like it could not parse go-edit.obo. But I don't see any obvious errors from you diff. I have restarted the travis checks just to see if it was a hiccup.

**Comment by ukemi** [comment]
One out of two passed. Let's try again. Third time is a charm.

**Review by ukemi — COMMENTED** [review]
Looked like nothing you did was wrong, just issues in the pipeline.

**Comment by tberardini** [comment]
Thanks for finishing this up.  Is restarting Travis checks something that I could have done?  I was looking for such a button/link last night but didn't see one.

**Comment by balhoff** [comment]
>  It seems that there is a file subsets/*.owl that can't be located. @dougli1sqrd or @balhoff do you know why this file is being called?

@ukemi is that still an issue?

**Comment by ukemi** [comment]
If you are logged in, you should be able to restart the check. The button only shows up when you are logged in. Seems like the file fixed itself @balhoff. It is still throwing the file not found statement though.

**Pull request merged**
