### PR TITLE
Added new term and the missing particle as pointed out by Paola Fixes…

### PR DESCRIPTION
**Pull request by BarbaraCzub**
… #14885 

Hi @ukemi the new term should be ok, but I also changed the label of a related term as @paolaroncaglia suggested: "GO:0005041 low-density lipoprotein receptor activity should be corrected to low-density lipoprotein _particle_ receptor activity". Could you please confirm that it is ok to merge this? 
Thanks,
Barbara

cc @RLovering

### CODE REVIEW

**Comment by BarbaraCzub** [comment]
oh no. I chose the wrong namespace... should I wait for the pending check to finish before editing this? Or can I edit and push again while this is running?

**Comment by ukemi** [comment]
Shouldn't the namespace be molecular_function?

**Comment by BarbaraCzub** [comment]
I have just corrected this. Yes.

**Comment by BarbaraCzub** [comment]
But I have noticed another error that I made...  I put the pull request number after 'Fixes' instead of the issue number. Is there a way to edit this?

**Comment by ukemi** [comment]
It shouldn't be a problem.

**Comment by BarbaraCzub** [comment]
Ok, thank you @ukemi, I'll merge now.

**Pull request merged**
