### PR TITLE
Added check for double whitespace, fixes #13202

### LINKED ISSUE #13202: Check for double whitespace in ontology labels
spotted by Bjoern Peters: some ontology terms have double whitespace in label

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Review by ukemi — COMMENTED** [review]
I don't see the errors listed anywhere in the output.

**Comment by cmungall** [comment]
ok, fixed, now does:

```
  :: ERROR: synonym has double-whitespace: line: synonym: "degradation of  host cell envelope lipopolysaccharide during viral entry" EXACT []
  :: ERROR: label has double-whitespace: line: name: positive  regulation of glutamatergic neuron differentiation
  :: ERROR: synonym has double-whitespace: line: synonym: "ANPR-A:ANF   NPR1:ANP    NPR1:ANF" RELATED []
```

**Comment by cmungall** [comment]
@ukemi - better now?

**Comment by ukemi** [comment]
Yup just fixed them. One was already fixed and the other were in synonyms. I fixed one and deleted the one from the obsolete term.

**Comment by cmungall** [comment]
Still gettting

```
../util/check-obo-for-standard-release.pl --disable-isa-incomplete --xref-abbs GO.xrf_abbs go-edit.obo > go-edit.obo-check.tmp && mv go-edit.obo-check.tmp go-edit.obo-check
 :: ERROR: synonym has double-whitespace: line: synonym: "degradation of  host cell envelope lipopolysaccharide during viral entry" EXACT []
 make: *** [go-edit.obo-check] Error 1
```

**Comment by pgaudet** [comment]
Hi @cmungall 
Do we need to fix these manually ? 

Pascale

**Comment by cmungall** [comment]
Yes. See ##13369

**Comment by cmungall** [comment]
It's done now

**Pull request merged**
