### PR TITLE
Remove regulates o part_of chains. Assert relations we wish to keep.

### LINKED ISSUE #12344: Remove regulates o part of -> regulates property chains
Therese property chains are useful as heuristics as often correct, but are also dangerous. Some processes (e.g. signal transduction) consist of a series of subprocesses/activities that form a causal/regulatory chain. These activities do not regulate the overall process. 

Recent example: inference of reg synaptic vesicle exocytosis - a key step in synaptic transmission - as a modulator of synaptic transmission.

NOTE: removal needs to be done with care given that many inferences are correct.  Need to think through how fits with ETINE review.

(Ticket might be better on RO? Also suspect this is at least partly addressed in other tickets)

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #12344 and #13926.

### CODE REVIEW

**Comment by balhoff** [comment]
@ukemi here is a diff including inferences: https://www.dropbox.com/s/evkvvmvz8fbwt7b/regulates-diff.html

To what extent do you want to try to review this?

**Comment by ukemi** [comment]
How huge is it? Can you put it in a spreadsheet with changed to Part_of and kept as regulates?

**Comment by balhoff** [comment]
@ukemi @pgaudet I've merged the latest `master` in this branch, so it could be merged if we want to merge. @ukemi were you happy with the changes here, even though there may have been additional hardcoded relations we may want to remove later?

**Comment by balhoff** [comment]
I met with @pgaudet today—the plan is to generate one more report, checking every subsumption from our Google spreadsheet and reporting whether any have not been removed when desired (or not been kept when desired).

**Comment by balhoff** [comment]
@pgaudet here is the report we talked about:

Relationships (possibly indirect) which you were not removed by deleting the property chain, but which you may want to remove from the ontology somehow:
- <http://purl.obolibrary.org/obo/GO_0051963> SubClassOf <http://purl.obolibrary.org/obo/GO_0044087>
- <http://purl.obolibrary.org/obo/GO_0090235> SubClassOf <http://purl.obolibrary.org/obo/GO_0010564>
- <http://purl.obolibrary.org/obo/GO_0099161> SubClassOf <http://purl.obolibrary.org/obo/GO_0023051>
- <http://purl.obolibrary.org/obo/GO_1903932> SubClassOf <http://purl.obolibrary.org/obo/GO_0090329>
- <http://purl.obolibrary.org/obo/GO_1904259> SubClassOf <http://purl.obolibrary.org/obo/GO_0045995>
- <http://purl.obolibrary.org/obo/GO_1905226> SubClassOf <http://purl.obolibrary.org/obo/GO_0043903>
- <http://purl.obolibrary.org/obo/GO_1905557> SubClassOf <http://purl.obolibrary.org/obo/GO_0007346>
- <http://purl.obolibrary.org/obo/GO_1905558> SubClassOf <http://purl.obolibrary.org/obo/GO_0010639>
- <http://purl.obolibrary.org/obo/GO_1905558> SubClassOf <http://purl.obolibrary.org/obo/GO_0045930>
- <http://purl.obolibrary.org/obo/GO_1905559> SubClassOf <http://purl.obolibrary.org/obo/GO_0010638>
- <http://purl.obolibrary.org/obo/GO_2000535> SubClassOf <http://purl.obolibrary.org/obo/GO_0043903>

Relationships (possibly indirect) which you were removed by deleting the property chain, but which you may want to add back somehow (either directly or by adding a regulates relation):
- <http://purl.obolibrary.org/obo/GO_0044127> SubClassOf <http://purl.obolibrary.org/obo/GO_0043903>
- <http://purl.obolibrary.org/obo/GO_0046928> SubClassOf <http://purl.obolibrary.org/obo/GO_0060341>
- <http://purl.obolibrary.org/obo/GO_0051611> SubClassOf <http://purl.obolibrary.org/obo/GO_0060341>
- <http://purl.obolibrary.org/obo/GO_0051802> SubClassOf <http://purl.obolibrary.org/obo/GO_0043903>
- <http://purl.obolibrary.org/obo/GO_0051940> SubClassOf <http://purl.obolibrary.org/obo/GO_0060341>
- <http://purl.obolibrary.org/obo/GO_0051941> SubClassOf <http://purl.obolibrary.org/obo/GO_0060341>
- <http://purl.obolibrary.org/obo/GO_0060694> SubClassOf <http://purl.obolibrary.org/obo/GO_0032374>
- <http://purl.obolibrary.org/obo/GO_0075184> SubClassOf <http://purl.obolibrary.org/obo/GO_0043903>
- <http://purl.obolibrary.org/obo/GO_0099145> SubClassOf <http://purl.obolibrary.org/obo/GO_0033157>
- <http://purl.obolibrary.org/obo/GO_0099145> SubClassOf <http://purl.obolibrary.org/obo/GO_0051128>
- <http://purl.obolibrary.org/obo/GO_0150044> SubClassOf <http://purl.obolibrary.org/obo/GO_0060341>
- <http://purl.obolibrary.org/obo/GO_1903548> SubClassOf <http://purl.obolibrary.org/obo/GO_0048519>
- <http://purl.obolibrary.org/obo/GO_1905407> SubClassOf <http://purl.obolibrary.org/obo/GO_1903789>
- <http://purl.obolibrary.org/obo/GO_1905408> SubClassOf <http://purl.obolibrary.org/obo/GO_0051956>
- <http://purl.obolibrary.org/obo/GO_1905409> SubClassOf <http://purl.obolibrary.org/obo/GO_0051957>
- <http://purl.obolibrary.org/obo/GO_1905598> SubClassOf <http://purl.obolibrary.org/obo/GO_0048261>
- <http://purl.obolibrary.org/obo/GO_1905700> SubClassOf <http://purl.obolibrary.org/obo/GO_2001024>
- <http://purl.obolibrary.org/obo/GO_1905701> SubClassOf <http://purl.obolibrary.org/obo/GO_2001025>

I think we could merge this PR, and still look into those two lists afterward. What do you think?

**Comment by pgaudet** [comment]
Discussed with @balhoff - let's merge this ! I'll look at the remaining issues.

**Pull request merged**
