### PR TITLE
Add check for one-to-one xrefs, e.g. RHEA.

### PR DESCRIPTION
**Pull request by balhoff**
@hdrabkin this check currently has two violations:

- http://purl.obolibrary.org/obo/GO_0033735
- http://purl.obolibrary.org/obo/GO_0120204

### CODE REVIEW

**Comment by hdrabkin** [comment]
I will fix these right now

**Comment by hdrabkin** [comment]
Did you fix these? I can only find the RHEAs used by these two terms only once

**Comment by balhoff** [comment]
This check looks for GO terms with more than one RHEA xref. I will update to also check for RHEA xrefs used with more than one GO term.

**Comment by balhoff** [comment]
@hdrabkin I added a check for RHEA xrefs used with more than one GO term:

- RHEA:33983 http://purl.obolibrary.org/obo/GO_0062205 http://purl.obolibrary.org/obo/GO_0102353
- RHEA:13349 http://purl.obolibrary.org/obo/GO_0102078 http://purl.obolibrary.org/obo/GO_0030795
- RHEA:19389 http://purl.obolibrary.org/obo/GO_0106287 http://purl.obolibrary.org/obo/GO_0050563
- RHEA:13957 http://purl.obolibrary.org/obo/GO_0033755 http://purl.obolibrary.org/obo/GO_0043826
- RHEA:30523 http://purl.obolibrary.org/obo/GO_0052619 http://purl.obolibrary.org/obo/GO_0043773
- RHEA:33655 http://purl.obolibrary.org/obo/GO_0015245 http://purl.obolibrary.org/obo/GO_1901480

**Pull request merged**
