### PR TITLE
Update taxon constraints

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the taxon constraints import. Check it out!

### CODE REVIEW

**Comment by balhoff** [comment]
@pgaudet something in the recent taxon constraint additions is causing a problem for http://purl.obolibrary.org/obo/GO_0097569.

**Comment by pgaudet** [comment]
Where is that coming from ? 

This term is_a 'cellular anatomical entity' - there is no taxon constraint on this term. Where this is coming from ?

**Comment by balhoff** [comment]
I checked out that branch from ontobot and I can't see any unsatisfiable classes. Not sure what's going on!

**Comment by balhoff** [comment]
Nevermind I got it, was just looking in the wrong place. Here is the explanation:

- 'lateral shield' SubClassOf 'part of' some 'cell body'
- 'cell body' SubClassOf 'only in taxon' some Metazoa
- Metazoa SubClassOf Opisthokonta
- 'lateral shield' SubClassOf 'only in taxon' some Giardia
- Giardia SubClassOf Giardiinae
- Giardiinae SubClassOf Hexamitidae
- Hexamitidae SubClassOf Diplomonadida
- Diplomonadida SubClassOf Fornicata
- Fornicata SubClassOf Metamonada
- 'only in taxon' SubPropertyOf: 'in taxon'
- 'in taxon' some Metamonada DisjointWith 'in taxon' some Opisthokonta
- 'part of' o 'in taxon' SubPropertyOf: 'in taxon'

**Comment by balhoff** [comment]
Problem is here: https://github.com/geneontology/go-ontology/pull/20748/files#r565438909

**Pull request closed without merging**
