### PR TITLE
added subclasses for EC 7 dot 5 per ticket 17127

### PR DESCRIPTION
**Pull request by hdrabkin**
different ways to transport carbohydrates and their derivatives

### CODE REVIEW

**Comment by pgaudet** [comment]
@hdrabkin 

It looks like some of your changes are overwriting a ticket I did earler today to fix incorrect ISBN (see diff of the PR). 
Can you got 'git pull origin master' in your branch, re-commit, and push again? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
this is already up to date when I did git pull master in my branch

**Comment by hdrabkin** [comment]
Did you merge your changes yet?

**Comment by pgaudet** [comment]
Yes - that's why they show up in your diff.

**Comment by hdrabkin** [comment]
So any idea how I can kill this ?

**Comment by pgaudet** [comment]
just close the PR

**Pull request closed without merging**
