### PR TITLE
check that detects replaced by classes that are deprecated but not merged

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by tberardini** [comment]
Failing checks seems bad omen.

**Comment by ukemi** [comment]
I think this is ok and the checks are working. See my comments on the ticket #15429

**Comment by dougli1sqrd** [comment]
@ukemi @tberardini does this work?

**Comment by ukemi** [comment]
Yes. I had actually already made this fix by hand in a branch and not pushed, but what I was asking in the ticket is whether or not we wanted to always fix these by hand or whether these errors could be handled programmatically. Sorry if I wasn't clear.

**Pull request merged**
