### PR TITLE
Refresh obsolete ECs file

### PR DESCRIPTION
**Pull request by ontobot**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by balhoff** [comment]
Need to check why this deletes a whole bunch of ids.

**Comment by balhoff** [comment]
@sjm41 new batch of obsolete EC terms. Here are the usages in GO:

- ERROR: <http://purl.obolibrary.org/obo/GO_0016844> has a definition xref to an obsolete EC: "EC:4.3.3.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0016844> has a synonym xref to an obsolete EC: "EC:4.3.3.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0016844> has an xref to an obsolete EC: "EC:4.3.3.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0030269> has a definition xref to an obsolete EC: "EC:2.1.1.86"
- ERROR: <http://purl.obolibrary.org/obo/GO_0030269> has a synonym xref to an obsolete EC: "EC:2.1.1.86"
- ERROR: <http://purl.obolibrary.org/obo/GO_0030269> has an xref to an obsolete EC: "EC:2.1.1.86"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050474> has a definition xref to an obsolete EC: "EC:4.2.1.78"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050474> has a synonym xref to an obsolete EC: "EC:4.2.1.78"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050474> has an xref to an obsolete EC: "EC:4.2.1.78"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050556> has a definition xref to an obsolete EC: "EC:4.3.3.3"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050556> has a synonym xref to an obsolete EC: "EC:4.3.3.3"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050556> has an xref to an obsolete EC: "EC:4.3.3.3"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050557> has a definition xref to an obsolete EC: "EC:4.3.3.4"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050557> has a synonym xref to an obsolete EC: "EC:4.3.3.4"
- ERROR: <http://purl.obolibrary.org/obo/GO_0050557> has an xref to an obsolete EC: "EC:4.3.3.4"

**Comment by sjm41** [comment]
Thanks @balhoff 

For now, I'll just note here the information about transfer etc:

EC 4.3.3.2
Transferred entry: [3.5.99.13](https://enzyme.expasy.org/EC/3.5.99.13)

EC 2.1.1.86
Transferred entry: [7.2.1.4](https://enzyme.expasy.org/EC/7.2.1.4)

EC 4.2.1.78
Transferred entry: [3.5.99.14](https://enzyme.expasy.org/EC/3.5.99.14)

EC 4.3.3.3
Transferred entry: [3.5.99.15](https://enzyme.expasy.org/EC/3.5.99.15)

EC 4.3.3.4
Transferred entry: [3.5.99.16](https://enzyme.expasy.org/EC/3.5.99.16)


So, the good news is that these 5 cases are all 1:1 transfers.
But the complication in each cases is the reaction/enzyme has changed its major classification (e.g. lyase to hydrolase), so we will need to review and change the parentage in GO.

**Comment by sjm41** [comment]
Hi @balhoff I believe I've just applied the fixes for those transferred ECs, so this pull request should now work.

**Comment by balhoff** [comment]
@sjm41 thanks!

**Pull request merged**
