### PR TITLE
Update ChEBI import

### PR DESCRIPTION
**Pull request by ontobot**
I've updated the ChEBI import. Here's a diff of how this impacts the classified ontology:

# Ontology comparison

## Old
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2021-09-01/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned-prev.owl`

## New
- Ontology IRI: `http://purl.obolibrary.org/obo/go.owl`
- Version IRI: `http://purl.obolibrary.org/obo/go/releases/2021-09-01/go.owl`
- Loaded from: `file:/projects/stars/jenkins-c8/workspace/GO/update-chebi-import/go-ontology/src/ontology/reasoned.owl`

#### Added
- [2-methylbutanoyl-CoA(4-) biosynthetic process](http://purl.obolibrary.org/obo/GO_1902191) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [2-methylbutanoyl-CoA(4-) catabolic process](http://purl.obolibrary.org/obo/GO_1902190) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [2-methylbutanoyl-CoA(4-) metabolic process](http://purl.obolibrary.org/obo/GO_1902189) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [bile acid binding](http://purl.obolibrary.org/obo/GO_0032052) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [bile acid catabolic process](http://purl.obolibrary.org/obo/GO_0030573) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [bile acid secretion](http://purl.obolibrary.org/obo/GO_0032782) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [diaminopimelate biosynthetic process](http://purl.obolibrary.org/obo/GO_0019877) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [diaminopimelate metabolic process](http://purl.obolibrary.org/obo/GO_0046451) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [fumarate metabolic process](http://purl.obolibrary.org/obo/GO_0006106) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [fumarate transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015138) SubClassOf [lipid transporter activity](http://purl.obolibrary.org/obo/GO_0005319) 

#### Added
- [fumarate transport](http://purl.obolibrary.org/obo/GO_0015741) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [icosanoid binding](http://purl.obolibrary.org/obo/GO_0050542) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [icosanoid biosynthetic process](http://purl.obolibrary.org/obo/GO_0046456) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [icosanoid metabolic process](http://purl.obolibrary.org/obo/GO_0006690) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [icosanoid transport](http://purl.obolibrary.org/obo/GO_0071715) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [isovaleryl-CoA(4-) biosynthetic process](http://purl.obolibrary.org/obo/GO_1902197) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [isovaleryl-CoA(4-) catabolic process](http://purl.obolibrary.org/obo/GO_1902196) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [isovaleryl-CoA(4-) metabolic process](http://purl.obolibrary.org/obo/GO_1902195) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [leukotriene A4 biosynthetic process](http://purl.obolibrary.org/obo/GO_1901753) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [leukotriene A4 catabolic process](http://purl.obolibrary.org/obo/GO_1901752) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [leukotriene A4 metabolic process](http://purl.obolibrary.org/obo/GO_1901751) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [leukotriene B4 biosynthetic process](http://purl.obolibrary.org/obo/GO_0097251) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Removed
- [leukotriene B4 catabolic process](http://purl.obolibrary.org/obo/GO_0036101) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Removed
- [leukotriene B4 metabolic process](http://purl.obolibrary.org/obo/GO_0036102) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [leukotriene catabolic process](http://purl.obolibrary.org/obo/GO_0036100) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [malonate catabolic process](http://purl.obolibrary.org/obo/GO_0090410) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [malonate(1-) transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_1901239) SubClassOf [lipid transporter activity](http://purl.obolibrary.org/obo/GO_0005319) 

#### Removed
- [malonic acid import across plasma membrane](http://purl.obolibrary.org/obo/GO_0098715) SubClassOf [import into cell](http://purl.obolibrary.org/obo/GO_0098657) 

#### Added
- [malonic acid import across plasma membrane](http://purl.obolibrary.org/obo/GO_0098715) SubClassOf [lipid import into cell](http://purl.obolibrary.org/obo/GO_0140354) 

#### Added
- [malonic acid transport](http://purl.obolibrary.org/obo/GO_1900752) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [negative regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120190) SubClassOf [negative regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032369) 

#### Added
- [negative regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901414) SubClassOf [negative regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0045833) 

#### Added
- [phosphatidylinositol-3,4-bisphosphate binding](http://purl.obolibrary.org/obo/GO_0043325) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [positive regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120189) SubClassOf [positive regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032370) 

#### Added
- [positive regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901415) SubClassOf [positive regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0045834) 

#### Removed
- [prostaglandin transport](http://purl.obolibrary.org/obo/GO_0015732) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [protocatechuate catabolic process, ortho-cleavage](http://purl.obolibrary.org/obo/GO_0019618) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [regulation of bile acid secretion](http://purl.obolibrary.org/obo/GO_0120188) SubClassOf [regulation of lipid transport](http://purl.obolibrary.org/obo/GO_0032368) 

#### Added
- [regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA](http://purl.obolibrary.org/obo/GO_1901413) SubClassOf [regulation of lipid metabolic process](http://purl.obolibrary.org/obo/GO_0019216) 

#### Removed
- [succinate import across plasma membrane](http://purl.obolibrary.org/obo/GO_0098720) SubClassOf [import into cell](http://purl.obolibrary.org/obo/GO_0098657) 

#### Added
- [succinate import across plasma membrane](http://purl.obolibrary.org/obo/GO_0098720) SubClassOf [lipid import into cell](http://purl.obolibrary.org/obo/GO_0140354) 

#### Added
- [succinate metabolic process](http://purl.obolibrary.org/obo/GO_0006105) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Added
- [succinate transmembrane transporter activity](http://purl.obolibrary.org/obo/GO_0015141) SubClassOf [lipid transporter activity](http://purl.obolibrary.org/obo/GO_0005319) 

#### Added
- [succinate transport](http://purl.obolibrary.org/obo/GO_0015744) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [succinyl-CoA binding](http://purl.obolibrary.org/obo/GO_0120226) SubClassOf [lipid binding](http://purl.obolibrary.org/obo/GO_0008289) 

#### Added
- [succinyl-CoA biosynthetic process](http://purl.obolibrary.org/obo/GO_1901290) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610) 

#### Added
- [succinyl-CoA catabolic process](http://purl.obolibrary.org/obo/GO_1901289) SubClassOf [lipid catabolic process](http://purl.obolibrary.org/obo/GO_0016042) 

#### Added
- [succinyl-CoA metabolic process](http://purl.obolibrary.org/obo/GO_0006104) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) 

#### Removed
- [thromboxane transport](http://purl.obolibrary.org/obo/GO_0071717) SubClassOf [lipid transport](http://purl.obolibrary.org/obo/GO_0006869) 

#### Added
- [tyrosine catabolic process to fumarate](http://purl.obolibrary.org/obo/GO_0019445) SubClassOf [lipid biosynthetic process](http://purl.obolibrary.org/obo/GO_0008610)

### CODE REVIEW

**Comment by pgaudet** [comment]
It seems to me some compounds here are not lipids - at least  succinate and tyrosine

@hdrabkin @deustp01 @ukemi What do you think? 

@balhoff Where are these new inferences coming from?

**Comment by ukemi** [comment]
You can't just look at the term name, you have to look at the logical def. According to ChEBI, fumarate (2-) is_a butenedioate and butenedioate is_a lipid. For succinate, they classify it as a lipid (seems odd to me, but it is soluble in acetone). The definition of a lipid is interesting in that it is based on solubility properties. @deustp01?

**Comment by deustp01** [comment]
Succinate is_a lipid? I'm confused. Here's a screenshot of part of the ontology for succinate (CHEBI:28606) and I don't see lipid or anything lipid-like in its parentage:
Screen Shot 2021-09-13 at 9 14 06 AM

Meanwhile, lipid (CHEBI:18059) has the definition, "'Lipids' is a loosely defined term for substances of biological origin that are soluble in nonpolar solvents. They consist of saponifiable lipids, such as glycerides (fats and oils) and phospholipids, as well as nonsaponifiable lipids, principally steroids." Note the "loosely defined" feature of the definition. I won't be able to look at textbooks until tomorrow, so I can't add more definitions from standard authorities until then, but my impression is that the definition is fuzzy, combining an imprecise solubility feature and an imprecise structural one. An additional complication is that lipids can be covalently attached to definitely non-lipid moieties, like the combination of a purine base and a monosaccharide in ATP, creating unexpected parentages - haven't dug far enough to see whether that's a factor in any of the unexpected classifications here..

**Comment by ukemi** [comment]
@deustp01 have a look at the parentage of succinate (2-). That's where I saw the lipid. I agree, the fuzzy def doesn't help. From the solubility standpoint, shouldn't they be insoluble in aqueous solutions too? They should form micelles at best????
I think we need to question ChEBI here.

**Comment by ukemi** [comment]
PS. I don't think the classifiactions here are based on any of the complications you point out. I think the stand-alone compounds are asserted to be lipids.

**Comment by alanbridge** [comment]
Hi all, 

hope you are doing well. I'm out the office at a conference at the moment so no not able to spend much time looking into textbook definitions, but according to accepted definitions of lipid from resources like LIPID MAPS it seems that succinate could be included.

e.g. from https://www.lipidmaps.org/resources/lipidweb/index.php?page=lipids/basics/Nomen/index.htm:

_Lipids comprise a heterogeneous class of predominantly hydrophobic organic molecules of relatively low molecular weight (commonly <1000), that are defined by the presence either of linear alkyl chains, usually with even-numbers of carbon atoms and saturated or unsaturated with double bonds in characteristic positions, or of isoprene units in linear or cyclic structures. These can contain variable numbers of oxygenated substituents such as carboxylic acid or hydroxyl groups, and/or other heteroatoms, but especially nitrogen in amines, for example. Often, these are linked covalently to glycerol, carbohydrates, phosphate and other small polar entities, which can render the molecules more amphiphilic._

Out of curiosity I ran succinate through the ClassyFire tool from the Wishart lab, which will classify input SMILES with respect to the CHEMONT ontology. ClassyFire does consider succinate to be a lipid, returning this among other things:

CHEMONTID:0000262 - Fatty acids and conjugates

Full results here: http://classyfire.wishartlab.com/queries/6575538

All the best, Alan 



</body>

</html>
"



<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/TEMP/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/TEMP/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



CHEMONTID:0000262 | Fatty acids and conjugates
-- | --




</body>

</html>

**Comment by deustp01** [comment]
> have a look at the parentage of succinate (2-)

Right. succinate 2-) is_a lipid; succinate (1-) is not. That has to be a mistake - the charge difference by itself should not de (dis)qualifying. My opinion is that neither entity should be a lipid. I've opened a ticket at CHEBI - https://github.com/ebi-chebi/ChEBI/issues/4136

**Comment by deustp01** [comment]
> lipid (CHEBI:18059) has the definition, "'Lipids' is a loosely defined term for substances of biological origin that are soluble in nonpolar solvents. They consist of saponifiable lipids, such as glycerides (fats and oils) and phospholipids, as well as nonsaponifiable lipids, principally steroids."

Now looking at textbooks (White et al., Principles of Biochemistry 6th edition 1978, page 38).

> "If animal or plant tissues are extracted with one or more of the so-called fat solvents, e.g., ethanol, ether, chloroform, benzene, or petroleum ether, a portion of the material dissolves; the name lipid is given to the components of this soluble fraction. ... Because of the heterogeneity of the structures it contains, the lipid fraction is often viewed as an operational rather than a structural classification and is defined simply as that fraction of any biological material extractable by solvents of low polarity."

Note that ethanol is not classified by CHEBI as a nonpolar solvent, adding to the fuzziness of the definitions / differentia here.

**Comment by hdrabkin** [comment]
There is a problem when the chemical in question can also dissolve in a polar solvent.
fumaric acid and succinic  are both water-soluble  in addition to being soluble in alcohol (furmaric acid) and acetone (succinic acid.

**Comment by ukemi** [comment]
Perhaps lipid should be a chebi role?

**Comment by deustp01** [comment]
> Perhaps lipid should be a chebi role?

Does that White et al. textbook definition identify a role? It sounds more like an experimental manipulation: the stuff that results when a tissue is subjected to a non-physiological laboratory manipulation - like "microsome", which is now seen, I guess, as neither a cell component nor a role?

**Comment by ukemi** [comment]
Good question, I was going out on a limb and thinking that being soluble in a nonpolar solvent was a role. It's a stretch.

**Comment by deustp01** [comment]
> Good question, I was going out on a limb and thinking that being soluble in a nonpolar solvent was a role. It's a stretch.

The operational grouping in the White definition is explicitly not based on a chemical property that is shared by all lipids and that distinguishes them from all other kinds of chemicals, so perhaps this is an occasion for replacing is_a relationships of specific chemical classes (fatty acid, sterol) to lipid with has_part ones. That would keep textbook biochemists reasonably happy and might work to defeat unwanted logical reasoning in GO? Or will this cause other problems? @alanbridge ? @hdrabkin ?

**Comment by ukemi** [comment]
There is also the option of just keeping things as they are and sticking to the ChEBI classification, even though on the surface some bits of the hierarchy aren't intuitive. Seems reasonable based on @alanbridge 's comment above.

**Comment by deustp01** [comment]
There is a formal ontology part to this that is beyond me. Alan's definition uses a list of differentia, which may be inelegant but is entirely workable. Is the fuzziness - "usually". "commonly", "often" - also OK? I guess that it is - perhaps the result is a definition that requires maintenance - tweaking the lists and explicitly adding exceptions to get correct reasoning?

**Comment by alanbridge** [comment]
Adnan commented (https://github.com/ebi-chebi/ChEBI/issues/4136): "if you ask two lipid researchers to define a lipid, you will get different answers" - I had the same experience when we started SwissLipids. I think lipids are generally thought of as a class rather than a role though. I'm sorry I can't help you more!

**Comment by ukemi** [comment]
No worries @alanbridge. Your comments are helpful. I'm tempted to just cast my vote as saying let ChEBI decide about the classification of lipids. I knew I was out on a limb with the role proposal,but it's nice to have someone pull me back.

**Comment by hdrabkin** [comment]
So do we ask CHEBI via tracker what exactly?

**Comment by hdrabkin** [comment]
Hi @alanbridge ; I have used the database https://www.lipidmaps.org/databases/lmsd/LMFA01170106?LMID=LMFA01170106 
succinic acid is listed as a fatty acid; fumaric acid is a retired entry, although 
LMFA01060194 | dihydroxy-fumaric acid |  

So I guess I don't understand what suggesting CHEBI to use this classification system will get us?

**Comment by pgaudet** [comment]
Chebi contacted  https://github.com/ebi-chebi/ChEBI/issues/4176#issuecomment-984226590
 to remove 
• fumarate transmembrane transporter activity SubClassOf lipid transporter activity
Added
• fumarate transport SubClassOf lipid transport
Added
• negative regulation of tetrapyrrole biosynthetic process from glycine and succinyl-CoA SubClassOf negative regulation of lipid metabolic process
Added
• succinate metabolic process SubClassOf lipid metabolic process
Added
• tyrosine catabolic process to fumarate SubClassOf lipid biosynthetic process

**Comment by balhoff** [comment]
## [succinyl-CoA metabolic process](http://purl.obolibrary.org/obo/GO_0006104) SubClassOf [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) ##

  - [succinyl-CoA metabolic process](http://purl.obolibrary.org/obo/GO_0006104) EquivalentTo [metabolic process](http://purl.obolibrary.org/obo/GO_0008152) and ([has primary input or output](http://purl.obolibrary.org/obo/RO_0004007) some [succinyl-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_57292))
    - [succinyl-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_57292) SubClassOf [omega-carboxy-(fatty acyl)-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_177898)
      - [omega-carboxy-(fatty acyl)-CoA(5-)](http://purl.obolibrary.org/obo/CHEBI_177898) SubClassOf [lipid](http://purl.obolibrary.org/obo/CHEBI_18059)
  - [lipid metabolic process](http://purl.obolibrary.org/obo/GO_0006629) EquivalentTo [metabolic process](http://purl.obolibrary.org/obo/GO_0008152) and ([has primary input or output](http://purl.obolibrary.org/obo/RO_0004007) some [lipid](http://purl.obolibrary.org/obo/CHEBI_18059))

**Comment by pgaudet** [comment]
@balhoff The Jan 1 CHEBI release was supposed to remove the links of fumaric acid, succinic acid, and malonic acid to lipid; can we start the import again and see if the problem is resolved? 

Thanks, Pascale

**Pull request closed without merging**
