### PR TITLE
Change logical definition references to substances, not roles.

### PR DESCRIPTION
**Pull request by balhoff**
Affect on GO classification:

126 inferences removed:
- SubClassOf(<GO:0015345>[ferric enterobactin:proton symporter activity] <GO:0008514>[organic anion transmembrane transporter activity])
- SubClassOf(<GO:0015345>[ferric enterobactin:proton symporter activity] <GO:1901618>[organic hydroxy compound transmembrane transporter activity])
- SubClassOf(<GO:0015624>[ATPase-coupled ferric-enterobactin transmembrane transporter activity] <GO:0008514>[organic anion transmembrane transporter activity])
- SubClassOf(<GO:0015624>[ATPase-coupled ferric-enterobactin transmembrane transporter activity] <GO:1901618>[organic hydroxy compound transmembrane transporter activity])
- SubClassOf(<GO:0019537>[vibriobactin biosynthetic process] <GO:0043604>[amide biosynthetic process])
- SubClassOf(<GO:0019537>[vibriobactin biosynthetic process] <GO:1901566>[organonitrogen compound biosynthetic process])
- SubClassOf(<GO:0032355>[response to estradiol] <GO:0009725>[response to hormone])
- SubClassOf(<GO:0033595>[response to genistein] <GO:0009725>[response to hormone])
- SubClassOf(<GO:0035936>[testosterone secretion] <GO:0046879>[hormone secretion])
- SubClassOf(<GO:0035936>[testosterone secretion] <GO:0140353>[lipid export from cell])
- SubClassOf(<GO:0035938>[estradiol secretion] <GO:0046879>[hormone secretion])
- SubClassOf(<GO:0035938>[estradiol secretion] <GO:0140353>[lipid export from cell])
- SubClassOf(<GO:0035941>[androstenedione secretion] <GO:0046879>[hormone secretion])
- SubClassOf(<GO:0035941>[androstenedione secretion] <GO:0140353>[lipid export from cell])
- SubClassOf(<GO:0035942>[dehydroepiandrosterone secretion] <GO:0046879>[hormone secretion])
- SubClassOf(<GO:0035942>[dehydroepiandrosterone secretion] <GO:0140353>[lipid export from cell])
- SubClassOf(<GO:0035943>[estrone secretion] <GO:0046879>[hormone secretion])
- SubClassOf(<GO:0035943>[estrone secretion] <GO:0140353>[lipid export from cell])
- SubClassOf(<GO:0043627>[response to estrogen] <GO:0050896>[response to stimulus])
- SubClassOf(<GO:0043636>[bisphenol A catabolic process] <GO:0042447>[hormone catabolic process])
- SubClassOf(<GO:0061370>[testosterone biosynthetic process] <GO:0120178>[steroid hormone biosynthetic process])
- SubClassOf(<GO:0071391>[cellular response to estrogen stimulus] <GO:0070887>[cellular response to chemical stimulus])
- SubClassOf(<GO:0071392>[cellular response to estradiol stimulus] <GO:0032870>[cellular response to hormone stimulus])
- SubClassOf(<GO:0071412>[cellular response to genistein] <GO:0032870>[cellular response to hormone stimulus])
- SubClassOf(<GO:1901732>[quercetin metabolic process] <GO:0042445>[hormone metabolic process])
- SubClassOf(<GO:1901733>[quercetin catabolic process] <GO:0042447>[hormone catabolic process])
- SubClassOf(<GO:1901734>[quercetin biosynthetic process] <GO:0042446>[hormone biosynthetic process])
- SubClassOf(<GO:1902124>[(+)-pinoresinol metabolic process] <GO:0042445>[hormone metabolic process])
- SubClassOf(<GO:1902125>[(+)-pinoresinol catabolic process] <GO:0042447>[hormone catabolic process])
- SubClassOf(<GO:1902126>[(+)-pinoresinol biosynthetic process] <GO:0042446>[hormone biosynthetic process])
- SubClassOf(<GO:1902136>[(-)-secoisolariciresinol metabolic process] <GO:0042445>[hormone metabolic process])
- SubClassOf(<GO:1902137>[(-)-secoisolariciresinol catabolic process] <GO:0042447>[hormone catabolic process])
- SubClassOf(<GO:1902138>[(-)-secoisolariciresinol biosynthetic process] <GO:0042446>[hormone biosynthetic process])
- SubClassOf(<GO:1903449>[androst-4-ene-3,17-dione biosynthetic process] <GO:0120178>[steroid hormone biosynthetic process])
- SubClassOf(<GO:1903455>[negative regulation of androst-4-ene-3,17-dione biosynthetic process] <GO:0010894>[negative regulation of steroid biosynthetic process])
- SubClassOf(<GO:1903455>[negative regulation of androst-4-ene-3,17-dione biosynthetic process] <GO:0032353>[negative regulation of hormone biosynthetic process])
- SubClassOf(<GO:1903925>[response to bisphenol A] <GO:0009725>[response to hormone])
- SubClassOf(<GO:1903926>[cellular response to bisphenol A] <GO:0032870>[cellular response to hormone stimulus])
- SubClassOf(<GO:1904486>[response to 17alpha-ethynylestradiol] <GO:0009725>[response to hormone])
- SubClassOf(<GO:1904487>[cellular response to 17alpha-ethynylestradiol] <GO:0032870>[cellular response to hormone stimulus])
- SubClassOf(<GO:1905235>[response to quercetin] <GO:0009725>[response to hormone])
- SubClassOf(<GO:1905236>[cellular response to quercetin] <GO:0032870>[cellular response to hormone stimulus])
- SubClassOf(<GO:2000225>[negative regulation of testosterone biosynthetic process] <GO:0010894>[negative regulation of steroid biosynthetic process])
- SubClassOf(<GO:2000225>[negative regulation of testosterone biosynthetic process] <GO:0032353>[negative regulation of hormone biosynthetic process])
- SubClassOf(<GO:2000837>[regulation of androstenedione secretion] <GO:0032368>[regulation of lipid transport])
- SubClassOf(<GO:2000837>[regulation of androstenedione secretion] <GO:0046883>[regulation of hormone secretion])
- SubClassOf(<GO:2000838>[negative regulation of androstenedione secretion] <GO:0032369>[negative regulation of lipid transport])
- SubClassOf(<GO:2000838>[negative regulation of androstenedione secretion] <GO:0046888>[negative regulation of hormone secretion])
- SubClassOf(<GO:2000839>[positive regulation of androstenedione secretion] <GO:0032370>[positive regulation of lipid transport])
- SubClassOf(<GO:2000839>[positive regulation of androstenedione secretion] <GO:0046887>[positive regulation of hormone secretion])
- SubClassOf(<GO:2000840>[regulation of dehydroepiandrosterone secretion] <GO:0032368>[regulation of lipid transport])
- SubClassOf(<GO:2000840>[regulation of dehydroepiandrosterone secretion] <GO:0046883>[regulation of hormone secretion])
- SubClassOf(<GO:2000841>[negative regulation of dehydroepiandrosterone secretion] <GO:0032369>[negative regulation of lipid transport])
- SubClassOf(<GO:2000841>[negative regulation of dehydroepiandrosterone secretion] <GO:0046888>[negative regulation of hormone secretion])
- SubClassOf(<GO:2000842>[positive regulation of dehydroepiandrosterone secretion] <GO:0032370>[positive regulation of lipid transport])
- SubClassOf(<GO:2000842>[positive regulation of dehydroepiandrosterone secretion] <GO:0046887>[positive regulation of hormone secretion])
- SubClassOf(<GO:2000843>[regulation of testosterone secretion] <GO:0032368>[regulation of lipid transport])
- SubClassOf(<GO:2000843>[regulation of testosterone secretion] <GO:0046883>[regulation of hormone secretion])
- SubClassOf(<GO:2000844>[negative regulation of testosterone secretion] <GO:0032369>[negative regulation of lipid transport])
- SubClassOf(<GO:2000844>[negative regulation of testosterone secretion] <GO:0046888>[negative regulation of hormone secretion])
- SubClassOf(<GO:2000845>[positive regulation of testosterone secretion] <GO:0032370>[positive regulation of lipid transport])
- SubClassOf(<GO:2000845>[positive regulation of testosterone secretion] <GO:0046887>[positive regulation of hormone secretion])
- SubClassOf(<GO:2000864>[regulation of estradiol secretion] <GO:0032368>[regulation of lipid transport])
- SubClassOf(<GO:2000864>[regulation of estradiol secretion] <GO:0046883>[regulation of hormone secretion])
- SubClassOf(<GO:2000865>[negative regulation of estradiol secretion] <GO:0032369>[negative regulation of lipid transport])
- SubClassOf(<GO:2000865>[negative regulation of estradiol secretion] <GO:0046888>[negative regulation of hormone secretion])
- SubClassOf(<GO:2000866>[positive regulation of estradiol secretion] <GO:0032370>[positive regulation of lipid transport])
- SubClassOf(<GO:2000866>[positive regulation of estradiol secretion] <GO:0046887>[positive regulation of hormone secretion])
- SubClassOf(<GO:2000867>[regulation of estrone secretion] <GO:0032368>[regulation of lipid transport])
- SubClassOf(<GO:2000867>[regulation of estrone secretion] <GO:0046883>[regulation of hormone secretion])
- SubClassOf(<GO:2000868>[negative regulation of estrone secretion] <GO:0032369>[negative regulation of lipid transport])
- SubClassOf(<GO:2000868>[negative regulation of estrone secretion] <GO:0046888>[negative regulation of hormone secretion])
- SubClassOf(<GO:2000869>[positive regulation of estrone secretion] <GO:0032370>[positive regulation of lipid transport])
- SubClassOf(<GO:2000869>[positive regulation of estrone secretion] <GO:0046887>[positive regulation of hormone secretion])

### CODE REVIEW

**Comment by balhoff** [comment]
133 axioms added:
+ SubClassOf(<GO:0006729>[tetrahydrobiopterin biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:0006747>[FAD biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:0006768>[biotin metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:0006783>[heme biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:0008559>[ATPase-coupled xenobiotic transmembrane transporter activity] <GO:0042910>[xenobiotic transmembrane transporter activity])
+ SubClassOf(<GO:0009102>[biotin biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:0009235>[cobalamin metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:0009236>[cobalamin biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:0009374>[biotin binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0015345>[ferric enterobactin:proton symporter activity] <GO:0042931>[enterobactin transmembrane transporter activity])
+ SubClassOf(<GO:0015411>[ATPase-coupled taurine transporter activity] <GO:0008559>[ATPase-coupled xenobiotic transmembrane transporter activity])
+ SubClassOf(<GO:0015624>[ATPase-coupled ferric-enterobactin transmembrane transporter activity] <GO:0042931>[enterobactin transmembrane transporter activity])
+ SubClassOf(<GO:0015903>[fluconazole transport] <GO:0042908>[xenobiotic transport])
+ SubClassOf(<GO:0019270>[aerobactin biosynthetic process] <GO:0019290>[siderophore biosynthetic process])
+ SubClassOf(<GO:0019271>[aerobactin transport] <GO:0015891>[siderophore transport])
+ SubClassOf(<GO:0019537>[vibriobactin biosynthetic process] <GO:0019290>[siderophore biosynthetic process])
+ SubClassOf(<GO:0020037>[heme binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0031419>[cobalamin binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0032355>[response to estradiol] <GO:0043627>[response to estrogen])
+ SubClassOf(<GO:0033595>[response to genistein] <GO:0043627>[response to estrogen])
+ SubClassOf(<GO:0034617>[tetrahydrobiopterin binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0035936>[testosterone secretion] <GO:0035935>[androgen secretion])
+ SubClassOf(<GO:0035938>[estradiol secretion] <GO:0035937>[estrogen secretion])
+ SubClassOf(<GO:0035941>[androstenedione secretion] <GO:0035935>[androgen secretion])
+ SubClassOf(<GO:0035942>[dehydroepiandrosterone secretion] <GO:0035935>[androgen secretion])
+ SubClassOf(<GO:0035943>[estrone secretion] <GO:0035937>[estrogen secretion])
+ SubClassOf(<GO:0042167>[heme catabolic process] <GO:0051190>[prosthetic group catabolic process])
+ SubClassOf(<GO:0042168>[heme metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:0042366>[cobalamin catabolic process] <GO:0051190>[prosthetic group catabolic process])
+ SubClassOf(<GO:0042367>[biotin catabolic process] <GO:0051190>[prosthetic group catabolic process])
+ SubClassOf(<GO:0043214>[ATPase-coupled bacteriocin transmembrane transporter activity] <GO:0008559>[ATPase-coupled xenobiotic transmembrane transporter activity])
+ SubClassOf(<GO:0043627>[response to estrogen] <GO:0009725>[response to hormone])
+ SubClassOf(<GO:0043636>[bisphenol A catabolic process] <GO:0006711>[estrogen catabolic process])
+ SubClassOf(<GO:0046146>[tetrahydrobiopterin metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:0046147>[tetrahydrobiopterin catabolic process] <GO:0051190>[prosthetic group catabolic process])
+ SubClassOf(<GO:0046443>[FAD metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:0051536>[iron-sulfur cluster binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0061370>[testosterone biosynthetic process] <GO:0006702>[androgen biosynthetic process])
+ SubClassOf(<GO:0070453>[regulation of heme biosynthetic process] <GO:0010556>[regulation of macromolecule biosynthetic process])
+ SubClassOf(<GO:0070453>[regulation of heme biosynthetic process] <GO:0051199>[regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:0070454>[negative regulation of heme biosynthetic process] <GO:0010558>[negative regulation of macromolecule biosynthetic process])
+ SubClassOf(<GO:0070454>[negative regulation of heme biosynthetic process] <GO:0051201>[negative regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:0070455>[positive regulation of heme biosynthetic process] <GO:0010557>[positive regulation of macromolecule biosynthetic process])
+ SubClassOf(<GO:0070455>[positive regulation of heme biosynthetic process] <GO:0051200>[positive regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:0071391>[cellular response to estrogen stimulus] <GO:0032870>[cellular response to hormone stimulus])
+ SubClassOf(<GO:0071392>[cellular response to estradiol stimulus] <GO:0071391>[cellular response to estrogen stimulus])
+ SubClassOf(<GO:0071412>[cellular response to genistein] <GO:0071391>[cellular response to estrogen stimulus])
+ SubClassOf(<GO:0071949>[FAD binding] <GO:0051192>[prosthetic group binding])
+ SubClassOf(<GO:0106064>[regulation of cobalamin metabolic process] <GO:0051199>[regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:0106121>[positive regulation of cobalamin metabolic process] <GO:0051200>[positive regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:0106122>[negative regulation of cobalamin metabolic process] <GO:0051201>[negative regulation of prosthetic group metabolic process])
+ SubClassOf(<GO:1901732>[quercetin metabolic process] <GO:0008210>[estrogen metabolic process])
+ SubClassOf(<GO:1901733>[quercetin catabolic process] <GO:0006711>[estrogen catabolic process])
+ SubClassOf(<GO:1901734>[quercetin biosynthetic process] <GO:0006703>[estrogen biosynthetic process])
+ SubClassOf(<GO:1901850>[7,8-didemethyl-8-hydroxy-5-deazariboflavin metabolic process] <GO:0051189>[prosthetic group metabolic process])
+ SubClassOf(<GO:1901851>[7,8-didemethyl-8-hydroxy-5-deazariboflavin catabolic process] <GO:0051190>[prosthetic group catabolic process])
+ SubClassOf(<GO:1901852>[7,8-didemethyl-8-hydroxy-5-deazariboflavin biosynthetic process] <GO:0051191>[prosthetic group biosynthetic process])
+ SubClassOf(<GO:1902124>[(+)-pinoresinol metabolic process] <GO:0008210>[estrogen metabolic process])
+ SubClassOf(<GO:1902125>[(+)-pinoresinol catabolic process] <GO:0006711>[estrogen catabolic process])
+ SubClassOf(<GO:1902126>[(+)-pinoresinol biosynthetic process] <GO:0006703>[estrogen biosynthetic process])
+ SubClassOf(<GO:1902136>[(-)-secoisolariciresinol metabolic process] <GO:0008210>[estrogen metabolic process])
+ SubClassOf(<GO:1902137>[(-)-secoisolariciresinol catabolic process] <GO:0006711>[estrogen catabolic process])
+ SubClassOf(<GO:1902138>[(-)-secoisolariciresinol biosynthetic process] <GO:0006703>[estrogen biosynthetic process])
+ SubClassOf(<GO:1902599>[sulfathiazole transmembrane transport] <GO:0042908>[xenobiotic transport])
+ SubClassOf(<GO:1903449>[androst-4-ene-3,17-dione biosynthetic process] <GO:0006702>[androgen biosynthetic process])
+ SubClassOf(<GO:1903455>[negative regulation of androst-4-ene-3,17-dione biosynthetic process] <GO:2000180>[negative regulation of androgen biosynthetic process])
+ SubClassOf(<GO:1903925>[response to bisphenol A] <GO:0043627>[response to estrogen])
+ SubClassOf(<GO:1903926>[cellular response to bisphenol A] <GO:0071391>[cellular response to estrogen stimulus])
+ SubClassOf(<GO:1904486>[response to 17alpha-ethynylestradiol] <GO:0043627>[response to estrogen])
+ SubClassOf(<GO:1904487>[cellular response to 17alpha-ethynylestradiol] <GO:0071391>[cellular response to estrogen stimulus])
+ SubClassOf(<GO:1905235>[response to quercetin] <GO:0043627>[response to estrogen])
+ SubClassOf(<GO:1905236>[cellular response to quercetin] <GO:0071391>[cellular response to estrogen stimulus])
+ SubClassOf(<GO:2000225>[negative regulation of testosterone biosynthetic process] <GO:2000180>[negative regulation of androgen biosynthetic process])
+ SubClassOf(<GO:2000837>[regulation of androstenedione secretion] <GO:2000834>[regulation of androgen secretion])
+ SubClassOf(<GO:2000838>[negative regulation of androstenedione secretion] <GO:2000835>[negative regulation of androgen secretion])
+ SubClassOf(<GO:2000839>[positive regulation of androstenedione secretion] <GO:2000836>[positive regulation of androgen secretion])
+ SubClassOf(<GO:2000840>[regulation of dehydroepiandrosterone secretion] <GO:2000834>[regulation of androgen secretion])
+ SubClassOf(<GO:2000841>[negative regulation of dehydroepiandrosterone secretion] <GO:2000835>[negative regulation of androgen secretion])
+ SubClassOf(<GO:2000842>[positive regulation of dehydroepiandrosterone secretion] <GO:2000836>[positive regulation of androgen secretion])
+ SubClassOf(<GO:2000843>[regulation of testosterone secretion] <GO:2000834>[regulation of androgen secretion])
+ SubClassOf(<GO:2000844>[negative regulation of testosterone secretion] <GO:2000835>[negative regulation of androgen secretion])
+ SubClassOf(<GO:2000845>[positive regulation of testosterone secretion] <GO:2000836>[positive regulation of androgen secretion])
+ SubClassOf(<GO:2000864>[regulation of estradiol secretion] <GO:2000861>[regulation of estrogen secretion])
+ SubClassOf(<GO:2000865>[negative regulation of estradiol secretion] <GO:2000862>[negative regulation of estrogen secretion])
+ SubClassOf(<GO:2000866>[positive regulation of estradiol secretion] <GO:2000863>[positive regulation of estrogen secretion])
+ SubClassOf(<GO:2000867>[regulation of estrone secretion] <GO:2000861>[regulation of estrogen secretion])
+ SubClassOf(<GO:2000868>[negative regulation of estrone secretion] <GO:2000862>[negative regulation of estrogen secretion])
+ SubClassOf(<GO:2000869>[positive regulation of estrone secretion] <GO:2000863>[positive regulation of estrogen secretion])

**Comment by balhoff** [comment]
@krchristie these just fix illogical direct references to roles (instead of GOCHE versions). Maybe I should remake the GOCHE logical definition diff after merging this.

**Comment by krchristie** [comment]
@balhoff - I think I need a little more info on what this one is doing.

**Comment by balhoff** [comment]
We have the GOCHE terms because roles are not chemicals; so we mirror the role hierarchy with ‘substance with X role’ to make chemical versions. There were a bunch of definitions in GO using role terms directly where chemicals should be. This should be prevented by the reasoner but there is an unfinished feature in ELK. 

I updated all these definitions to use ‘substance with X role’ instead of ‘X’. This will result in classifications that were missing, and then will change somewhat when we stop autoclassifying other chemicals under these substance terms.

**Pull request merged**
