### PR TITLE
Reactome xrefs import

### PR DESCRIPTION
**Pull request by goodb**
This request handles bringing in Reactome xrefs from an externally provided mapping file.  It uses DOSDP to generate an ontology that contains the xrefs and then imports the ontology into the GO.  Could use touch ups relating to handling of non-ascii chars in import file (it just deletes them thought there are only a few) and most likely there is better Makefile logic that could be written.  But it seems to work and we need it done soon so.. here it is.

### CODE REVIEW

**Review by ukemi — DISMISSED** [review]
I couldn't load the ontology from this branch into Protege.

**Comment by goodb** [comment]
@goodb did you run the Makefile with Docker?  The import would need to be generated that way until this is executed on the production server and thus could be downloaded directly from there when you load Protege.

**Comment by ukemi** [comment]
No. That would explain why the file isn't there.

**Comment by balhoff** [comment]
@goodb the way most of the imports work is that they are kept in version control, and periodically regenerated manually. So if you did it that way, the local file would be loaded via the catalog XML.

**Comment by goodb** [comment]
@balhoff the makefile will regenerate the import whenever it is run as it stands now.  Yes, I edited the catalogue.xml file to point to its local version and yes, that will report a problem before the make is made.  It is different from the other imports. Perhaps there is a different pattern that would make more sense to the editors.

**Comment by ukemi** [comment]
Running docker on the branch now. I will give a report at the meeting.

**Comment by goodb** [comment]
Let me know if it doesn’t work.  Maybe it can be fixed before the meeting.  If something is wrong it ought to be a minor fix

**Comment by ukemi** [comment]
It seems to have worked. But there are tons of un-tracked files, including the new imports.

**Pull request merged**
