### PR TITLE
Add EC to one-to-one-xrefs-by-value-violation.sparql

### PR DESCRIPTION
**Pull request by balhoff**
These ECs are currently xrefs for multiple GO terms (and are causing this PR to fail checks):

----
Added to spreadsheet
https://docs.google.com/spreadsheets/d/17QvDQoIXe-Rim9ReReVlZGntr-WkIGJ0cbPhaQDB_As/edit#gid=0
----

2024-07-15 - updated list:

 - [ ] EC:3.5.1.108 — http://purl.obolibrary.org/obo/GO_0103117 http://purl.obolibrary.org/obo/GO_0008759
 - [ ] EC:2.7.1.138 — http://purl.obolibrary.org/obo/GO_0102773 http://purl.obolibrary.org/obo/GO_0001729
 - [ ] EC:3.2.1.147 — http://purl.obolibrary.org/obo/GO_0019137 http://purl.obolibrary.org/obo/GO_0102799
 - [ ] EC:3.5.4.4 — http://purl.obolibrary.org/obo/GO_0004000 http://purl.obolibrary.org/obo/GO_0046936
 - [ ] EC:2.6.1.96 — http://purl.obolibrary.org/obo/GO_0102351 http://purl.obolibrary.org/obo/GO_0034387
 - [ ] EC:2.1.1.267 — http://purl.obolibrary.org/obo/GO_0070448 http://purl.obolibrary.org/obo/GO_0033799
 - [ ] EC:2.4.1.227 — http://purl.obolibrary.org/obo/GO_0050511 http://purl.obolibrary.org/obo/GO_0051991
 - [ ] EC:2.5.1.48 — http://purl.obolibrary.org/obo/GO_0003962 http://purl.obolibrary.org/obo/GO_0102028
 - [ ] EC:2.7.10.2 — http://purl.obolibrary.org/obo/GO_0004713 http://purl.obolibrary.org/obo/GO_0004715
 - [ ] EC:2.7.1.91 — http://purl.obolibrary.org/obo/GO_0017050 http://purl.obolibrary.org/obo/GO_0008481
 - [ ] EC:3.2.2.21 — http://purl.obolibrary.org/obo/GO_0003905 http://purl.obolibrary.org/obo/GO_0052821 http://purl.obolibrary.org/obo/GO_0052822 http://purl.obolibrary.org/obo/GO_0043916 http://purl.obolibrary.org/obo/GO_0008725
 - [ ] EC:3.1.1.26 — http://purl.obolibrary.org/obo/GO_0047714 http://purl.obolibrary.org/obo/GO_0102549
 - [ ] EC:2.4.1.234 — http://purl.obolibrary.org/obo/GO_0102479 http://purl.obolibrary.org/obo/GO_0033834
 - [ ] EC:3.1.3.75 — http://purl.obolibrary.org/obo/GO_0052731 http://purl.obolibrary.org/obo/GO_0052732
 - [ ] EC:2.1.1.146 — http://purl.obolibrary.org/obo/GO_0102719 http://purl.obolibrary.org/obo/GO_0050630
 - [ ] EC:5.1.99.6 — http://purl.obolibrary.org/obo/GO_0052856 http://purl.obolibrary.org/obo/GO_0052857
 - [ ] EC:3.1.2.3 — http://purl.obolibrary.org/obo/GO_0047617 http://purl.obolibrary.org/obo/GO_0004778
 - [ ] EC:3.1.1.32 — http://purl.obolibrary.org/obo/GO_0008970 http://purl.obolibrary.org/obo/GO_0052739 http://purl.obolibrary.org/obo/GO_0052740
 - [ ] EC:3.1.1.14 — http://purl.obolibrary.org/obo/GO_0102293 http://purl.obolibrary.org/obo/GO_0047746
 - [ ] EC:2.4.1.242 — http://purl.obolibrary.org/obo/GO_0033840 http://purl.obolibrary.org/obo/GO_0102502
 - [ ] EC:2.5.1.21 — http://purl.obolibrary.org/obo/GO_0051996 http://purl.obolibrary.org/obo/GO_0004310
 - [ ] EC:3.6.1.58 — http://purl.obolibrary.org/obo/GO_0044715 http://purl.obolibrary.org/obo/GO_0044716
 - [ ] EC:4.3.2.2 — http://purl.obolibrary.org/obo/GO_0004018 http://purl.obolibrary.org/obo/GO_0070626
 - [ ] EC:3.1.3.62 — http://purl.obolibrary.org/obo/GO_0052826 http://purl.obolibrary.org/obo/GO_0004446
 - [ ] EC:2.3.1.176 — http://purl.obolibrary.org/obo/GO_0033814 http://purl.obolibrary.org/obo/GO_0050632
 - [ ] EC:2.7.8.13 — http://purl.obolibrary.org/obo/GO_0051992 http://purl.obolibrary.org/obo/GO_0008963
 - [ ] EC:2.4.1.253 — http://purl.obolibrary.org/obo/GO_0102468 http://purl.obolibrary.org/obo/GO_0102467 http://purl.obolibrary.org/obo/GO_0102159
 - [ ] EC:3.5.5.1 — http://purl.obolibrary.org/obo/GO_0080061 http://purl.obolibrary.org/obo/GO_0000257
 - [ ] EC:3.5.1.25 — http://purl.obolibrary.org/obo/GO_0008448 http://purl.obolibrary.org/obo/GO_0047419
 - [ ] EC:3.4.13.18 — http://purl.obolibrary.org/obo/GO_0016805 http://purl.obolibrary.org/obo/GO_0103046
 - [ ] EC:3.1.3.56 — http://purl.obolibrary.org/obo/GO_0052658 http://purl.obolibrary.org/obo/GO_0052659 http://purl.obolibrary.org/obo/GO_0004445
 - [ ] EC:2.3.1.181 — http://purl.obolibrary.org/obo/GO_0016415 http://purl.obolibrary.org/obo/GO_0033819
 - [ ] EC:2.1.1.42 — http://purl.obolibrary.org/obo/GO_0030744 http://purl.obolibrary.org/obo/GO_0102822
 - [ ] EC:7.1.2.2 — http://purl.obolibrary.org/obo/GO_0046961 http://purl.obolibrary.org/obo/GO_0046933
 - [ ] EC:2.4.1.1 — http://purl.obolibrary.org/obo/GO_0004645 http://purl.obolibrary.org/obo/GO_0102250 http://purl.obolibrary.org/obo/GO_0102499
 - [ ] EC:1.13.11.- — http://purl.obolibrary.org/obo/GO_0016702 http://purl.obolibrary.org/obo/GO_0019114 http://purl.obolibrary.org/obo/GO_0019117
 - [ ] EC:3.1.3.43 — http://purl.obolibrary.org/obo/GO_0004741 http://purl.obolibrary.org/obo/GO_0019909
 - [ ] EC:6.3.2.11 — http://purl.obolibrary.org/obo/GO_0047730 http://purl.obolibrary.org/obo/GO_0102102
 - [ ] EC:5.3.99.8 — http://purl.obolibrary.org/obo/GO_0052728 http://purl.obolibrary.org/obo/GO_0052727
 - [ ] EC:6.3.2.10 — http://purl.obolibrary.org/obo/GO_0047480 http://purl.obolibrary.org/obo/GO_0008766
 - [ ] EC:2.5.1.104 — http://purl.obolibrary.org/obo/GO_0043918 http://purl.obolibrary.org/obo/GO_0043919
 - [ ] EC:2.1.1.157 — http://purl.obolibrary.org/obo/GO_0052730 http://purl.obolibrary.org/obo/GO_0052729
 - [ ] EC:3.1.3.25 — http://purl.obolibrary.org/obo/GO_0008934 http://purl.obolibrary.org/obo/GO_0052832 http://purl.obolibrary.org/obo/GO_0052834 http://purl.obolibrary.org/obo/GO_0052833
 - [ ] EC:1.1.1.170 — http://purl.obolibrary.org/obo/GO_0047012 http://purl.obolibrary.org/obo/GO_0103067 http://purl.obolibrary.org/obo/GO_0103066 http://purl.obolibrary.org/obo/GO_0000252
 - [ ] EC:2.4.2.8 — http://purl.obolibrary.org/obo/GO_0004422 http://purl.obolibrary.org/obo/GO_0052657
 - [ ] EC:2.4.1.21 — http://purl.obolibrary.org/obo/GO_0009011 http://purl.obolibrary.org/obo/GO_0033201
 - [ ] EC:2.1.1.162 — http://purl.obolibrary.org/obo/GO_0052730 http://purl.obolibrary.org/obo/GO_0052729
 - [ ] EC:4.2.1.84 — http://purl.obolibrary.org/obo/GO_0018822 http://purl.obolibrary.org/obo/GO_0080109
 - [ ] EC:3.2.1.162 — http://purl.obolibrary.org/obo/GO_0033957 http://purl.obolibrary.org/obo/GO_0102255
 - [ ] EC:3.1.3.16 — http://purl.obolibrary.org/obo/GO_0004722 http://purl.obolibrary.org/obo/GO_0017018
 - [ ] EC:2.7.11.11 — http://purl.obolibrary.org/obo/GO_0004679 http://purl.obolibrary.org/obo/GO_0004691
 - [ ] EC:3.2.1.2 — http://purl.obolibrary.org/obo/GO_0102229 http://purl.obolibrary.org/obo/GO_0016161
 - [ ] EC:3.1.3.108 — http://purl.obolibrary.org/obo/GO_0102757 http://purl.obolibrary.org/obo/GO_0019178
 - [ ] EC:7.4.2.5 — http://purl.obolibrary.org/obo/GO_0015462 http://purl.obolibrary.org/obo/GO_0015440
 - [ ] EC:1.17.99.4 — http://purl.obolibrary.org/obo/GO_0050383 http://purl.obolibrary.org/obo/GO_0043835 http://purl.obolibrary.org/obo/GO_0052620
 - [ ] EC:3.4.23.- — http://purl.obolibrary.org/obo/GO_0042500 http://purl.obolibrary.org/obo/GO_0004190
 - [ ] EC:5.1.3.9 — http://purl.obolibrary.org/obo/GO_0009385 http://purl.obolibrary.org/obo/GO_0047465
 - [ ] EC:3.4.11.- — http://purl.obolibrary.org/obo/GO_0016284 http://purl.obolibrary.org/obo/GO_0004177
 - [ ] EC:1.7.2.3 — http://purl.obolibrary.org/obo/GO_0009033 http://purl.obolibrary.org/obo/GO_0050626
 - [ ] EC:3.7.1.14 — http://purl.obolibrary.org/obo/GO_0052823 http://purl.obolibrary.org/obo/GO_0018771
 - [ ] EC:1.14.13.8 — http://purl.obolibrary.org/obo/GO_0047822 http://purl.obolibrary.org/obo/GO_0004499
 - [ ] EC:2.3.1.1 — http://purl.obolibrary.org/obo/GO_0004042 http://purl.obolibrary.org/obo/GO_0103045
 - [ ] EC:1.1.1.110 — http://purl.obolibrary.org/obo/GO_0047722 http://purl.obolibrary.org/obo/GO_0047029 http://purl.obolibrary.org/obo/GO_0097256
 - [ ] EC:2.8.1.9 — http://purl.obolibrary.org/obo/GO_0008265 http://purl.obolibrary.org/obo/GO_0102867
 - [ ] EC:4.3.1.25 — http://purl.obolibrary.org/obo/GO_0052883 http://purl.obolibrary.org/obo/GO_0045548
 - [ ] EC:2.6.1.42 — http://purl.obolibrary.org/obo/GO_0004084 http://purl.obolibrary.org/obo/GO_0052655 http://purl.obolibrary.org/obo/GO_0052656 http://purl.obolibrary.org/obo/GO_0052654
 - [ ] EC:1.1.1.51 — http://purl.obolibrary.org/obo/GO_0035410 http://purl.obolibrary.org/obo/GO_0030283
 - [ ] EC:7.-.-.- — http://purl.obolibrary.org/obo/GO_0106178 http://purl.obolibrary.org/obo/GO_0015399
 - [ ] EC:6.2.1.- — http://purl.obolibrary.org/obo/GO_0018853 http://purl.obolibrary.org/obo/GO_0016878
 - [ ] EC:4.6.-.- — http://purl.obolibrary.org/obo/GO_0042408 http://purl.obolibrary.org/obo/GO_0016849
 - [ ] EC:1.5.3.13 — http://purl.obolibrary.org/obo/GO_0052901 http://purl.obolibrary.org/obo/GO_0052904 http://purl.obolibrary.org/obo/GO_0052902 http://purl.obolibrary.org/obo/GO_0052903 http://purl.obolibrary.org/obo/GO_0052899
 - [ ] EC:1.5.3.14 — http://purl.obolibrary.org/obo/GO_0052900 http://purl.obolibrary.org/obo/GO_0052896 http://purl.obolibrary.org/obo/GO_0052893
 - [ ] EC:1.5.3.16 — http://purl.obolibrary.org/obo/GO_0052901 http://purl.obolibrary.org/obo/GO_0052894 http://purl.obolibrary.org/obo/GO_0052895
 - [ ] EC:1.1.1.353 — http://purl.obolibrary.org/obo/GO_0102974 http://purl.obolibrary.org/obo/GO_0102975 http://purl.obolibrary.org/obo/GO_0102976
 - [ ] EC:2.6.1.50 — http://purl.obolibrary.org/obo/GO_0047310 http://purl.obolibrary.org/obo/GO_0080100
 - [ ] EC:1.5.3.17 — http://purl.obolibrary.org/obo/GO_0052901 http://purl.obolibrary.org/obo/GO_0052902 http://purl.obolibrary.org/obo/GO_0046592
 - [ ] EC:2.4.1.80 — http://purl.obolibrary.org/obo/GO_0102769 http://purl.obolibrary.org/obo/GO_0008120
 - [ ] EC:3.2.1.52 — http://purl.obolibrary.org/obo/GO_0102148 http://purl.obolibrary.org/obo/GO_0004563
 - [ ] EC:2.7.9.4 — http://purl.obolibrary.org/obo/GO_0050521 http://purl.obolibrary.org/obo/GO_0102216 http://purl.obolibrary.org/obo/GO_0102218
 - [ ] EC:2.7.9.5 — http://purl.obolibrary.org/obo/GO_0051752 http://purl.obolibrary.org/obo/GO_0102219 http://purl.obolibrary.org/obo/GO_0102217
 - [ ] EC:3.1.11.- — http://purl.obolibrary.org/obo/GO_0016895 http://purl.obolibrary.org/obo/GO_0008856
 - [ ] EC:3.2.1.18 — http://purl.obolibrary.org/obo/GO_0052795 http://purl.obolibrary.org/obo/GO_0052794 http://purl.obolibrary.org/obo/GO_0004308 http://purl.obolibrary.org/obo/GO_0052796
 - [ ] EC:2.7.1.73 — http://purl.obolibrary.org/obo/GO_0008906 http://purl.obolibrary.org/obo/GO_0106366
 - [ ] EC:3.2.1.21 — http://purl.obolibrary.org/obo/GO_0102483 http://purl.obolibrary.org/obo/GO_0008422
 - [ ] EC:3.1.1.64 — http://purl.obolibrary.org/obo/GO_0052885 http://purl.obolibrary.org/obo/GO_0052884
 - [ ] EC:3.5.1.4 — http://purl.obolibrary.org/obo/GO_0004040 http://purl.obolibrary.org/obo/GO_0043864
 - [ ] EC:4.2.1.- — http://purl.obolibrary.org/obo/GO_0018128 http://purl.obolibrary.org/obo/GO_0018135 http://purl.obolibrary.org/obo/GO_0016836

### CODE REVIEW

**Comment by sjm41** [comment]
Thanks Jim! Does this list filter out obsolete terms (which may still have EC refs attached, as discussed?

Also, my favourite example seems missing - I see 42 terms with EC:1.13.11.- xref

**Comment by balhoff** [comment]
> Thanks Jim! Does this list filter out obsolete terms (which may still have EC refs attached, as discussed?

Ah—this does include obsolete terms. Currently we enforce this over both current and obsolete terms for Rhea xrefs. One way we could retain this check but avoid on obsolete terms is to change the mappings scope to something besides exact (the default assumption) or narrow. It could be "related".

> Also, my favourite example seems missing - I see 42 terms with EC:1.13.11.- xref

Thanks for checking that; I had a problem copying out of Github logs. I edited my comment.

**Comment by sjm41** [comment]
Thanks Jim - that list more-or-less matches my simple grep over the last released go-basic.obo file.
I think we should keep the obsolete terms in this list for now - as discussed early in today's call, it's possible (likely) that the EC xref on the obsolete term should be removed by the rules we agreed.

**Comment by pgaudet** [comment]
@balhoff Can we merge this??

**Pull request merged**
