### PR TITLE
ribulose-phosphate 3-epimerase activity renamed and added a synonym. …

### LINKED ISSUE #22506: ribulose-phosphate 3-epimerase activity add synonym
ribulose-phosphate 3-epimerase activity
Add exact? synonym
pentose phosphate epimerase (PPE)
PMID:9872416

### PR DESCRIPTION
**Pull request by raymond91125**
…Fixes #22506

### CODE REVIEW

**Comment by pgaudet** [comment]
Does the synonym 'pentose phosphate epimerase (PPE)' cove both the D and the L substrates? If that's the case, I would make it a BROAD synonym.

**Comment by raymond91125** [comment]
In the context of PMID:9872416, I believe it's only the D- form.

**Comment by ValWood** [comment]
> Does the synonym 'pentose phosphate epimerase (PPE)' cove both the D and the L substrates? If that's the case, I would make it a BROAD synonym.

I don't know. This was a really old paper, and didn't mention different isomers of
ribulose-5-phosphate 3-epimerase.

Note, should these comments move to the ticket?
This is the pull request.
Peter  might know, he is very knowledgeable about glucose metabolism in general

**Comment by deustp01** [comment]
> Peter might know,

Sorry, no clue here.

**Comment by raymond91125** [comment]
comments copied over to the ticket #22506

**Pull request merged**
